### PR TITLE
feat: APP-115 account merging

### PR DESCRIPTION
**Pull request by blushi**
## Description

Needs https://github.com/regen-network/regen-server/pull/467

https://regennetwork.atlassian.net/browse/APP-115?atlOrigin=eyJpIjoiYmJiMTFlYWU5NzBjNGU1YzhlOWZhOGZjYTA4ZjQ0OTgiLCJwIjoiaiJ9

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

From https://deploy-preview-2370--regen-marketplace.netlify.app/profile/edit/settings
1. Log in with a web2 account and try to connect a wallet address that is already used by another account
2. Choose to keep the current account and verify that your profile remains the same and all projects from both accounts have been merged into the current account
3. Log out and redo 1. but choose to keep the web3 account. Verify that profile data is now the one from the web3 account and all projects from both accounts have been merged into the web3 account

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie @clevinson see testing instructions

**Review by aaronc — APPROVED** [review]
utACK

**Comment by erikalogie** [comment]
@blushi I merged the accounts but the keplr account is not showing up in the settings:

https://github.com/regen-network/regen-web/assets/8460237/9d6493d1-aa68-4fb8-b6ae-ba248bed0c7a

**Review by clevinson — APPROVED** [review]
Tested and it works as expected. Thanks @blushi !

Two issues that came up while I was testing (unrelated to this PR):
- bug related to uploading photos on profile not working at all on dev app (https://regennetwork.atlassian.net/browse/APP-190)
-  nice to have follow up feature for enabling the removing of a keplr wallet address from a merged account (https://regennetwork.atlassian.net/browse/APP-191)

**Comment by erikalogie** [comment]
> > @blushi I merged the accounts but the keplr account is not showing up in the settings:
> > Screen.Recording.2024-06-18.at.7.06.27.AM.mov
> 
> Looks like you didn't quite get the full flow, because the modal to choose which account to keep didn't get displayed, some error happened on the way, I'll try to look at the server logs.

Could this be because neither of these accounts have any projects? I was going to test again and add some projects to see if that was it.

**Comment by erikalogie** [comment]
I don't think that we should show this popup "https://monosnap.com/file/tUzRw9oKemT4lLxW0UDCqaKGDJWFKo" if neither account has any profile data (as I did while testing).

**Comment by blushi** [comment]
> I don't think that we should show this popup "https://monosnap.com/file/tUzRw9oKemT4lLxW0UDCqaKGDJWFKo" if neither account has any profile data (as I did while testing).
> 
> But if this is complicated and will take some time to accomplish, maybe better to leave it.

So in this case, we would just default to keep the current account?

**Comment by erikalogie** [comment]
> > I don't think that we should show this popup "https://monosnap.com/file/tUzRw9oKemT4lLxW0UDCqaKGDJWFKo" if neither account has any profile data (as I did while testing).
> > But if this is complicated and will take some time to accomplish, maybe better to leave it.
> 
> So in this case, we would just default to keep the current account?

What do you mean by this? If neither account has changed the name or added any other profile info, it would just stay like that on account merging, without needing to select either of the accounts.

**Comment by blushi** [comment]
> > > I don't think that we should show this popup "https://monosnap.com/file/tUzRw9oKemT4lLxW0UDCqaKGDJWFKo" if neither account has any profile data (as I did while testing).
> > > But if this is complicated and will take some time to accomplish, maybe better to leave it.
> > 
> > 
> > So in this case, we would just default to keep the current account?
> 
> What do you mean by this? If neither account has changed the name or added any other profile info, it would just stay like that on account merging, without needing to select either of the accounts.

Yeah I guess for the user it doesn't really matter in this case, but in the db, we would still need to keep one account and delete the other, that's what I meant. The easiest is just to keep the current account I guess because we don't really need to update the cookie session.

**Comment by blushi** [comment]
> > > > @blushi I merged the accounts but the keplr account is not showing up in the settings:
> > > > Screen.Recording.2024-06-18.at.7.06.27.AM.mov
> > > 
> > > 
> > > Looks like you didn't quite get the full flow, because the modal to choose which account to keep didn't get displayed, some error happened on the way, I'll try to look at the server logs.
> > 
> > 
> > Could this be because neither of these accounts have any projects? I was going to test again and add some projects to see if that was it.
> 
> It seems to work when the accounts have projects.

I'm not able to reproduce this even with accounts without any projects.
Which wallet address were you using? Because I can see that this account with email 'pakopew788@luravell.com' now has some address associated to it: regen153h437xap3psstqrdw72rghsj8cly3k97d2ppd

**Comment by blushi** [comment]
> I don't think that we should show this popup "https://monosnap.com/file/tUzRw9oKemT4lLxW0UDCqaKGDJWFKo" if neither account has any profile data (as I did while testing).
> 
> But if this is complicated and will take some time to accomplish, maybe better to leave it.

I've added this. In addition to profile data, I'm also checking that both accounts have the same type (user/org) to be able to merge directly without showing this popup.

**Comment by erikalogie** [comment]
> > I don't think that we should show this popup "https://monosnap.com/file/tUzRw9oKemT4lLxW0UDCqaKGDJWFKo" if neither account has any profile data (as I did while testing).
> > But if this is complicated and will take some time to accomplish, maybe better to leave it.
> 
> I've added this. In addition to profile data, I'm also checking that both accounts have the same type (user/org) to be able to merge directly without showing this popup.

Perfect!

**Comment by erikalogie** [comment]
> > > > > @blushi I merged the accounts but the keplr account is not showing up in the settings:
> > > > > Screen.Recording.2024-06-18.at.7.06.27.AM.mov
> > > > 
> > > > 
> > > > Looks like you didn't quite get the full flow, because the modal to choose which account to keep didn't get displayed, some error happened on the way, I'll try to look at the server logs.
> > > 
> > > 
> > > Could this be because neither of these accounts have any projects? I was going to test again and add some projects to see if that was it.
> > 
> > 
> > It seems to work when the accounts have projects.
> 
> I'm not able to reproduce this even with accounts without any projects. Which wallet address were you using? Because I can see that this account with email '[pakopew788@luravell.com](mailto:pakopew788@luravell.com)' now has some address associated to it: regen153h437xap3psstqrdw72rghsj8cly3k97d2ppd

Yes this is the account I was using. After adding projects to both accounts then I could merge them.

**Comment by erikalogie** [comment]
> > > > I don't think that we should show this popup "https://monosnap.com/file/tUzRw9oKemT4lLxW0UDCqaKGDJWFKo" if neither account has any profile data (as I did while testing).
> > > > But if this is complicated and will take some time to accomplish, maybe better to leave it.
> > > 
> > > 
> > > So in this case, we would just default to keep the current account?
> > 
> > 
> > What do you mean by this? If neither account has changed the name or added any other profile info, it would just stay like that on account merging, without needing to select either of the accounts.
> 
> Yeah I guess for the user it doesn't really matter in this case, but in the db, we would still need to keep one account and delete the other, that's what I meant. The easiest is just to keep the current account I guess because we don't really need to update the cookie session.

Yeah the current account is perfect.

**Comment by erikalogie** [comment]
@blushi I was just testing this again, and if I log in with an email address, the profile and the settings page are not loading, I just get this spinner forever

https://github.com/regen-network/regen-web/assets/8460237/070211c5-2761-4462-bddd-e079cb2faffe

**Comment by erikalogie** [comment]
> @blushi I was just testing this again, and if I log in with an email address, the profile and the settings page are not loading, I just get this spinner forever
> 
>  Screen.Recording.2024-06-20.at.8.58.59.AM.mov

Ok now I just logged out, logged in with keplr, then logged out of keplr, and logged back in and profile and settings pages are loading. Not sure what's going on.

**Comment by erikalogie** [comment]
I'm still getting the issue that the merging is not happening when I have two accounts with no projects:

https://github.com/regen-network/regen-web/assets/8460237/4f02f29d-7610-4c64-88be-64881904b974

I made a new keplr account for this, and a new email account, didn't make any changes to the profile or add any projects, and this is what I get when I try to merge in the keplr account from the email account.

**Comment by blushi** [comment]
> @blushi I was just testing this again, and if I log in with an email address, the profile and the settings page are not loading, I just get this spinner forever
> 
>  Screen.Recording.2024-06-20.at.8.58.59.AM.mov

Could you tell which steps you took exactly to log in? were you on this page before logging in (after logging out from another account)? what happens if you reload? I don't think this is related to the changes in this PR but this could be a separate bug to fix.

**Comment by blushi** [comment]
> I'm still getting the issue that the merging is not happening when I have two accounts with no projects:
> 
>  Screen.Recording.2024-06-20.at.9.02.49.AM.mov 
> I made a new keplr account for this, and a new email account, didn't make any changes to the profile or add any projects, and this is what I get when I try to merge in the keplr account from the email account.

I'm unable to reproduce this even with brand new accounts without projects. Could you do this again but with your dev tools open and the network tab in particular, when clicking on "merge", you should have a new request, if it's red, an error happened and it'll be helpful for me to see the "preview" tab for this request.

**Comment by erikalogie** [comment]
> https://deploy-preview-2370--regen-marketplace.netlify.app/profile/edit/settings

I just tried this again and it is working. I have no idea why it didn't work previously!

**Comment by erikalogie** [comment]
> > @blushi I was just testing this again, and if I log in with an email address, the profile and the settings page are not loading, I just get this spinner forever
> > Screen.Recording.2024-06-20.at.8.58.59.AM.mov
> 
> Could you tell which steps you took exactly to log in? were you on this page before logging in (after logging out from another account)? what happens if you reload? I don't think this is related to the changes in this PR but this could be a separate bug to fix.

I closed the window, but I haven't seen this happen again since that first time. If I notice it again I will definitely take closer note of the process and file a separate bug.

**Comment by blushi** [comment]
> > > @blushi I was just testing this again, and if I log in with an email address, the profile and the settings page are not loading, I just get this spinner forever
> > > Screen.Recording.2024-06-20.at.8.58.59.AM.mov
> > 
> > 
> > Could you tell which steps you took exactly to log in? were you on this page before logging in (after logging out from another account)? what happens if you reload? I don't think this is related to the changes in this PR but this could be a separate bug to fix.
> 
> I closed the window, but I haven't seen this happen again since that first time. If I notice it again I will definitely take closer note of the process and file a separate bug.

Okay do you believe we can merge this then? @erikalogie

**Comment by erikalogie** [comment]
> > > > @blushi I was just testing this again, and if I log in with an email address, the profile and the settings page are not loading, I just get this spinner forever
> > > > Screen.Recording.2024-06-20.at.8.58.59.AM.mov
> > > 
> > > 
> > > Could you tell which steps you took exactly to log in? were you on this page before logging in (after logging out from another account)? what happens if you reload? I don't think this is related to the changes in this PR but this could be a separate bug to fix.
> > 
> > 
> > I closed the window, but I haven't seen this happen again since that first time. If I notice it again I will definitely take closer note of the process and file a separate bug.
> 
> Okay do you believe we can merge this then? @erikalogie

Yes

**Pull request merged**
