### PR TITLE
chore: implement changes to project create flow buttons

### PR DESCRIPTION
**Pull request by blushi**
## Description

Closes: regen-network/rnd-dev-team#1871

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

From https://deploy-preview-2323--regen-marketplace.netlify.app/
1. Login
1. Create or edit a draft project and check the footer has the changes specified in https://github.com/regen-network/rnd-dev-team/issues/1871. In particular, test "Save draft & exit" button
2. Continue until the Review step where the button is "Submit" instead of "Save and next"

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie see testing instructions

**Comment by erikalogie** [comment]
@blushi the "save draft & exit" button should save and exit me from the form, but it does not do that if I am on a form page where I have not yet entered any info

Also can you make these buttons the same height on mobile? https://monosnap.com/file/RIBIJ9dGFUoKB6UMbo4qhQLg1b4ts9

**Comment by blushi** [comment]
> @blushi the "save draft & exit" button should save and exit me from the form, but it does not do that if I am on a form page where I have not yet entered any info

It does save and exit from the form for me. Could you send a vid of what's happening for you? And the project uuid you're using?

> Also can you make these buttons the same height on mobile? https://monosnap.com/file/RIBIJ9dGFUoKB6UMbo4qhQLg1b4ts9

this is fixed

**Comment by erikalogie** [comment]
> > @blushi the "save draft & exit" button should save and exit me from the form, but it does not do that if I am on a form page where I have not yet entered any info
> 
> It does save and exit from the form for me. Could you send a vid of what's happening for you? And the project uuid you're using?

I couldn't reproduce it this time so I think it is ok

> 
> > Also can you make these buttons the same height on mobile? https://monosnap.com/file/RIBIJ9dGFUoKB6UMbo4qhQLg1b4ts9
> 
> this is fixed

Great

All LGTM

**Comment by aaronc** [comment]
"Save Draft & Exit" doesn't work unless the current form validates. I tried to do this at the location step and the button didn't work until I had a valid location and there is no user feedback that this is necessary. It just seems like the button doesn't work.

**Comment by clevinson** [comment]
@blushi since Erika is out this week and we want to keep things moving, can we just have the "Save draft & exit" button not appear until you have completed the required fields? Or let's allow for the draft to be saved without required fields filled out.

**Comment by aaronc** [comment]
I think saving a draft shouldn't require validation to pass.

**Comment by blushi** [comment]
> Ok I'll try to check how we can bypass validation with react-hook-form

@clevinson @aaronc added as part of https://github.com/regen-network/regen-web/pull/2323/commits/b32b58c292f13e1ca796144bfa1b13c441feb243

**Comment by clevinson** [comment]
I'm getting a strange behavior in that the "Save draft & exit" is not working properly if the project size field is empty.

This is true both when:
- initially creating a project: the "Project Name" does not save if you press "Save draft & exit" with the "Project Size" field left blank
- editing an existing project: if you clear the text in the "Project Size" field and press "Save draft & exit" then no changes are saved

2 final thoughts (though I'm open to feedback if there's reason to keep it as is):
-  on the final "Review" page, can we change the name of the button from "Submit" to "Publish" ? I think 'publish' is more clear, as submit implies it may be reviewed by a 3rd party.
- I think we should add back the "Save draft & exit" button on the final review page. As a user may enter all of the data and still not want to publish yet if they are waiting for a specific day to publish the draft.

**Comment by blushi** [comment]
> I'm getting a strange behavior in that the "Save draft & exit" is not working properly if the project size field is empty.
> 
> This is true both when:
> 
> * initially creating a project: the "Project Name" does not save if you press "Save draft & exit" with the "Project Size" field left blank
> * editing an existing project: if you clear the text in the "Project Size" field and press "Save draft & exit" then no changes are saved


This should be fixed.

> 
> 2 final thoughts (though I'm open to feedback if there's reason to keep it as is):
> 
> * on the final "Review" page, can we change the name of the button from "Submit" to "Publish" ? I think 'publish' is more clear, as submit implies it may be reviewed by a 3rd party.
> * I think we should add back the "Save draft & exit" button on the final review page. As a user may enter all of the data and still not want to publish yet if they are waiting for a specific day to publish the draft.

Updated

**Comment by erikalogie** [comment]
LGTM!

**Comment by clevinson** [comment]
Looks good to me!

@blushi and I discovered a small bug which we should follow-up with as a separate PR, as its quite an edge case.

In summary: If a user goes back to a required page and unsets the field, when they later go in to edit the project they will be immediately directed to the last page they filled out. This creates a situation where a user can publish a project with some required fields unset.

**Review by clevinson — APPROVED** [review]

**Pull request merged**
