### PR TITLE
feat: use default class image

### PR DESCRIPTION
**Pull request by blushi**
## Description

Closes: regen-network/regen-registry#1764

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

https://deploy-preview-2004--regen-registry.netlify.app/credit-classes/C06

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie you can see this on https://deploy-preview-2004--regen-registry.netlify.app/credit-classes/C06

**Comment by erikalogie** [comment]
@blushi do you think that I should supply a higher res version in the case that there is nothing in the right hand column and the image is stretched like this?

**Review by wgwz — APPROVED** [review]
utACK

**Comment by blushi** [comment]
> @blushi do you think that I should supply a higher res version in the case that there is nothing in the right hand column and the image is stretched like this?
> 
> I could also provide an svg of just the icon itself

Higher res works

**Comment by erikalogie** [comment]
Credit class default image
 ok here is a higher res version

**Comment by erikalogie** [comment]
looks good!

**Pull request merged**
