### PR TITLE
fix: APP-262 APP-303 create post files rendering

### PR DESCRIPTION
**Pull request by r41ph**
## Description

https://regennetwork.atlassian.net/browse/APP-262

APP-263 looks fixed too: https://regennetwork.atlassian.net/browse/APP-263

---

### Author Checklist

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1. Create a New Post in a project and upload files to verify the files thumbnail doesn't overflow its container.  I have used .csv, .docx, .xls, .mp3, .mp4 and .json files while working on this. (APP-262)
2. In the Project Page, verify that the Share Link icon is not cut. (APP-263)

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by r41ph** [comment]
@erikalogie @clevinson see testing instructions

**Comment by erikalogie** [comment]
> Details

LGTM!

**Review by blushi — COMMENTED** [review]
On the post page, the file preview on the map looks a bit shifted to the right, see https://deploy-preview-2436--regen-marketplace.netlify.app/post/regen:13toVg51tcwo2J82Jc5JUmjLbKahxVdDgLcmwvTwFMgU2h5L7gc4Ptt.rdf
VS on dev: https://dev.app.regen.network/post/regen:13toVg51tcwo2J82Jc5JUmjLbKahxVdDgLcmwvTwFMgU2h5L7gc4Ptt.rdf

**Comment by blushi** [comment]
@r41ph now we don't see the top of the file:

image

VS on dev:

image

**Comment by r41ph** [comment]
@blushi @erikalogie this is been fixed, please have a look.

**Review by blushi — APPROVED** [review]
tACK

**Pull request merged**
