### PR TITLE
App 488 fix small language issues in terrasos app

### PR DESCRIPTION
**Pull request by S4mmyb**
## Description

Closes: #XXXX or regen-network/rnd-dev-team#XXXX

Hey @blushi , made some small changes to fix the language. The one thing I wasn't sure on is the `owner`. In the `ProjectDetails.Stakeholders.tsx` file I updated the name/description for `owner` to `custodian`, but I'm guessing this will affect other things in our app. With that in mind, can we get away with just changing it in the `es.po` and `en.po` files? 

Also I don't have the app up and running locally yet so wasn't able to test locally 😬 

---

### Author Checklist

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@S4mmyb I've generated the updated .po files, you can check the new translations on https://deploy-preview-2553--terrasos.netlify.app/project/test-terrasos-project

**Review by blushi — APPROVED** [review]

**Comment by S4mmyb** [comment]
great, thanks @blushi. This looks good, though I'm noticing that for some of the role descriptions (hover-overs) we use bold font and name the role, and for others we dont. Should we fix that really quick?

image
image

**Comment by blushi** [comment]
> great, thanks @blushi. This looks good, though I'm noticing that for some of the role descriptions (hover-overs) we use bold font and name the role, and for others we dont. Should we fix that really quick?
> 
> image image

This is how it is on figma: https://www.figma.com/design/brkxGV5qNOkZUp0YQl1cxO/Terrasos-Phase-1?node-id=1714-84211&node-type=instance&m=dev but I agree this is a bit inconsistent.
Thoughts @erikalogie?

**Comment by S4mmyb** [comment]
LGTM!

**Pull request merged**
