### PR TITLE
fix: APP-409 set retiring to true when payment is card

### PR DESCRIPTION
**Pull request by r41ph**
## Description

https://regennetwork.atlassian.net/browse/APP-409

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1. https://deploy-preview-2545--regen-marketplace.netlify.app/project/mai-ndombe-4/buy
2. Select crypto and then Buy tradable ecocredits
3. Swap back to card and back again to crypto - verify that the Crypto purchase options is set to Retire credits now

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by r41ph** [comment]
@erikalogie see testing instructions

**Comment by r41ph** [comment]
@erikalogie see testing instructions

**Comment by erikalogie** [comment]
@r41ph could you add some credits to buy with credit card, I forget how to do that

**Comment by r41ph** [comment]
@erikalogie you can use this project https://deploy-preview-2545--regen-marketplace.netlify.app/project/mai-ndombe-4/buy

**Comment by erikalogie** [comment]
Yeah on this one I can't buy any credit card credits, that tab is greyed out

**Comment by r41ph** [comment]
Are you using the testing user? if so try logging out and see if you can see the fiat credits

**Review by blushi — APPROVED** [review]

**Comment by blushi** [comment]
tACK

**Comment by erikalogie** [comment]
LGTM

**Pull request merged**
