### PR TITLE
feat: add project partners

### PR DESCRIPTION
**Pull request by blushi**
## Description

Needs: https://github.com/regen-network/regen-server/pull/444
Closes: regen-network/rnd-dev-team#1857

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

https://deploy-preview-2301--regen-marketplace.netlify.app/project/prefinance-project

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by aaronc — APPROVED** [review]
utACK pending testing

**Comment by blushi** [comment]
@erikalogie @aaronc you can test this on https://deploy-preview-2301--regen-marketplace.netlify.app/project/prefinance-project

**Comment by erikalogie** [comment]
@blushi this looks great! Just one small non-blocking suggestion is to move the "read more" up by 10px on mobile so it feels more connected with the "partners" block of info: https://monosnap.com/file/iMHLEsRa025Tbd9hCkGs39boPBi6hN

**Comment by blushi** [comment]
> @blushi this looks great! Just one small non-blocking suggestion is to move the "read more" up by 10px on mobile so it feels more connected with the "partners" block of info: https://monosnap.com/file/iMHLEsRa025Tbd9hCkGs39boPBi6hN

@erikalogie  this is done

**Comment by erikalogie** [comment]
> https://deploy-preview-2301--regen-marketplace.netlify.app/project/prefinance-project

Wonderful!

**Comment by erikalogie** [comment]
@blushi looks great! Is this going live today?

**Comment by blushi** [comment]
> @blushi looks great! Is this going live today?

Likely not, we need a separate release PR that will need to be approved by @aaronc

**Comment by erikalogie** [comment]
> > @blushi looks great! Is this going live today?
> 
> Likely not, we need a separate release PR that will need to be approved by @aaronc

Ah ok, would have been nice for the presentation today but ok.

**Pull request merged**
