### PR TITLE
chore: merge dev

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Merge dev into master with the latest development.

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed
- [ ] once the PR is closed, set up backport PRs for `redwood`, `hambach` and optionally `master` (see below)

#### Setting up backport PRs

After merging your PR to `dev`, set up backports by doing the following:

1. If your branch does not have merge commits, add the following comment to
   your PR:

- If PR is a new feature: `@Mergifyio backport redwood hambach`.
- If PR is a bug fix: `@Mergifyio backport redwood hambach master`.

2. If your branch does have merge commits:

   a. Pull latest `dev`, `hambach` and `redwood` branches

   b. Create new branches for backports and merge `dev` (replace `<PR#>` with your PR #)

   ```
   git checkout -b hambach-backport-<PR#> hambach
   git merge dev
   git push origin hambach-backport-<PR#>
   git checkout -b redwood-backport-<PR#> redwood
   git merge dev
   git push origin redwood-backport-<PR#>`
   ```

   c. Open new PRs in regen-web targeting `hambach` and `redwood`, respectively.

   d. If PR is a bug fix repeat the same process for `master` branch.

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by victordelval** [comment]
@flagrede doing some testing txs, I see that 2 things happen, related to the wallet i guess:

https://deploy-preview-1562--regen-registry.netlify.app
 
1. In the home: The first Tx you try to do after refreshing the browser, the message appears as if the reject button had finally been pressed in the Keplr dialog. And the Keplr dialog remains with the spinner buttons. After that, if you try again, the Tx goes well... but the following happens

2. Anywhere else to do some kind of Txs I see the Keplr window remains after commit, even when the Tx completes successfully....

Image for 1:
Screenshot from 2022-11-16 12-08-25

Image for 2:
Screenshot from 2022-11-16 12-05-16

**Comment by mhagel** [comment]
This exposes the Bridge Tab in the dashboard. We may want to tie that to a feature flag?

**Comment by mhagel** [comment]
Testing-wise, this is working well for me. Tested:

-create sell order
-buy
-retire
- clicked around site to different pages - looks good

**Review by mhagel — APPROVED** [review]
I am ok with adding the Bridge feature flag separately to keep this moving.

**Pull request merged**
