### PR TITLE
feat: add secondary button to EcologicalCreditCard

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/rnd-dev-team#1829
Needs: https://github.com/regen-network/regen-sanity/pull/52

- handle optional offset generation methods for ecological cards
- handle secondary button to ecological cards

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by blushi — APPROVED** [review]
looks good
probably worth having @erikalogie check the preview too: https://deploy-preview-2237--regen-website.netlify.app/

**Comment by blushi** [comment]
Not related but I've realized the three dots are a bit cut out below the featured credit cards, I'll create an issue to fix that

image

**Comment by erikalogie** [comment]
Just double-checking, I will still be able to add "project activities" to the ERA Brazil card?

**Comment by blushi** [comment]
@erika good to merge this?

**Pull request merged**
