### PR TITLE
feat: prefinance project page

### PR DESCRIPTION
**Pull request by blushi**
## Description

Closes: #2278

Since https://github.com/regen-network/regen-web/pull/2288 (prefinance project card) is not merged yet and I needed the changes from there, I've based my work on this existing work.

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

https://deploy-preview-2292--regen-marketplace.netlify.app/project/prefinance-project

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie you can test this on https://deploy-preview-2292--regen-marketplace.netlify.app/project/prefinance-project

**Comment by erikalogie** [comment]
@blushi this looks great! 

A few small things:
- There should be a little bit more space between "price" and the number in the pinned bottom nav and the whole price block should be vertically centered with the buttons: https://monosnap.com/file/kHezjwD9Un289tKUY8XyGF4luu4cyL
- The 2nd, 3rd, etc lines in "what you support enables" should line up with the text in the first line: https://monosnap.com/file/jBIN86AyzbyOanzolFLo0U9YQDCPSj
- Let's hide the "book a call" button on mobile as it doesn't fit
- This prefinance tag font should be smaller on mobile: https://monosnap.com/file/yP4BuJ5IBJrMbySnCbiLjBRbNNzbGt

**Review by aaronc — APPROVED** [review]
Pre-approving pending @erikalogie's approval

**Comment by erikalogie** [comment]
Looks good!

**Pull request merged**
