### PR TITLE
chore: remove ghost pages

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/regen-registry#1924

- remove ghost pages from both `web-www` and `web-registry`
- redirect old ghost pages URLs to either `regen.network` or `app.regen.network`

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1. https://deploy-preview-1926--steady-dodol-4090c8.netlify.app/

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie you can check that all ghost pages are being redirected to the home.
For the marketing website, these URL will return a `308` HTTP status meaning that the bots will cache the redirection forever (which is good). On the other hand for registry the redirection is being done client side, this might or not be enough for the bots to remove these pages from indexing. We might need to add the registry redirections to the domain level as well.

**Comment by erikalogie** [comment]
> @erikalogie you can check that all ghost pages are being redirected to the home. For the marketing website, these URL will return a ~`308` HTTP status meaning that the bots will cache the redirection forever (which is good)~, actually will change to 307 (temporary redirection) as we might need to reuse these URLs someday (might be safer but let me know if you still think we should do a permanent one. From what I read it could take up to a month to reindex a URL that has been permanently redirected before). ~On the other hand for registry the redirection is being done client side, this might or not be enough for the bots to remove these pages from indexing. We might need to add the registry redirections to the domain level as well~. Never mind I just added it in Netlify config as well.

307 seems fine to me. 

Where can I check this? I still see the /case-studies pages on the live site.

**Comment by flagrede** [comment]
@erikalogie sorry for that, forgot to send you the links.
Here's the one for the marketing website: https://deploy-preview-1926--steady-dodol-4090c8.netlify.app/
Here's the one for registry: https://deploy-preview-1926--regen-registry.netlify.app/
For the registry one you can only see the client-side redirection, but on prod it will redirect earlier when resolving the URL.

**Review by wgwz — APPROVED** [review]
utACK

**Comment by erikalogie** [comment]
> @erikalogie sorry for that, forgot to send you the links. Here's the one for the marketing website: https://deploy-preview-1926--steady-dodol-4090c8.netlify.app/ Here's the one for registry: https://deploy-preview-1926--regen-registry.netlify.app/ For the registry one you can only see the client-side redirection, but on prod it will redirect earlier when resolving the URL.

Ok great, I think we are missing the redirect for https://deploy-preview-1926--steady-dodol-4090c8.netlify.app/case-studies. Sorry that url should have been written out more explicitly in the notion doc. 

Most of the other links do not seem to work/redirect for the website, except for the individual case study pages. They all look like
this for me: https://monosnap.com/file/kHXYQE2wohb4AUAenbvKOeZweH823Y. i.e. https://deploy-preview-1926--steady-dodol-4090c8.netlify.app/developers

You did not remove the /land-stewards page on the registry, correct? I still see it, I just wanted to make sure as that one we want to keep. There was some back and forth in the comments that may have made it confusing.

**Comment by erikalogie** [comment]
> @erikalogie ok, there was something odd happening, should be better, all links on https://deploy-preview-1926--steady-dodol-4090c8.netlify.app should be good. I added https://deploy-preview-1926--steady-dodol-4090c8.netlify.app/case-studies to the list. I removed https://app.regen.network/land-stewards/ from the production redirection list. Just note that in prod it is already redirecting to https://app.regen.network/project-developers

Looks great!

**Pull request merged**
