### PR TITLE
feat: APP-461 remove filters for Terrasos and change pagination to 9

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: APP-461

Remove filters for Terrasos and change pagination to 9 projects per page.

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by blushi — APPROVED** [review]
Tested locally, pending @erikalogie to test this once you set up VITE_MARKETPLACE_CLIENT=terrasos for this branch @flagrede

**Comment by flagrede** [comment]
@erikalogie You can check that the filters have been removed for Terrasos here: https://deploy-preview-2542--regen-marketplace.netlify.app/projects/1

**Comment by erikalogie** [comment]
LGTM!

**Comment by erikalogie** [comment]
I just noticed that this spacing looks like not enough now:
Monosnap Terrasos – Inversiones para la Conservación de la Biodiversidad 2024-11-14 08-13-48

**Comment by blushi** [comment]
> I just noticed that this spacing looks like not enough now: Monosnap Terrasos – Inversiones para la Conservación de la Biodiversidad 2024-11-14 08-13-48

I'll take care of that in the filters PR since we're adding the "add filters" button in between so it could interfer.

**Pull request merged**
