### PR TITLE
feat: add credit class filter

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/regen-registry#1730

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1. https://deploy-preview-1971--regen-registry.netlify.app/projects/1

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie you can test the credit class filter here: https://deploy-preview-1971--regen-registry.netlify.app/projects/1

**Comment by erikalogie** [comment]
@flagrede this looks great! It is a bit different from how I envisioned but it looks good like this so I would just make some small modification to move the "community credit class" filter into the side bar. https://monosnap.com/file/qFJkdWUKQ3oQFYyqhGCJ07wZ0isNxb

Also, the "reset filters" link/button shouldn't appear until after the user has set some filters.

**Review by ryanchristo — COMMENTED** [review]
Looking good.

Should pagination be updated when filters are applied?

Screenshot from 2023-07-17 12-23-49

Also wondering if there is any reason we should consider leveraging the query for projects by class? Probably not as we want all projects either way but just noting we have the option.

Code looks good. Pending changes requested by @erikalogie.

**Comment by ryanchristo** [comment]
> Should pagination be updated when filters are applied?

Also wondering if there should be some sort of message about there being no projects that meet the filter criteria. Looking at the image again, seems strange to only see the pagination navigation and no projects.

**Comment by erikalogie** [comment]
There is an empty state graphic that I designed for this that could be implemented @ryanchristo: https://www.figma.com/file/seUiQM2SPt78KJiDL0Ea8m/Basic-Ecocredits-Ledger-View-%2F-Marketplace?type=design&node-id=3272%3A162138&mode=design&t=oYJtDfSz5Wylwqyz-1

**Comment by flagrede** [comment]
@erikalogie I've handled your feedback.
@ryanchristo The pagination is now updated accordingly to the filters applied. We are already using the projects by class query whenever a class id is specified.

**Review by blushi — COMMENTED** [review]
Should we hide the class with id `VITE_SKIPPED_CLASS_ID` from the credit class filter?
Is that intended not to show the community credit classes in the credit class filter even when the "show community credits" is on? If we want to change that in this case, we should probably get the credit class name from the class metadata instead of sanity and if no name, just show the id, like we do on the credit class page.

**Comment by flagrede** [comment]
@blushi I think we should hide skipped credit class indeed, I fixed that.

@erikalogie Should we display all community credit classes in the new filter or not necessarily?

**Comment by erikalogie** [comment]
> @blushi I think we should hide skipped credit class indeed, I fixed that.
> 
> @erikalogie Should we display all community credit classes in the new filter or not necessarily?

Yes I suppose we should add them to the list after the user clicks "show community credits"

**Comment by flagrede** [comment]
@erikalogie you can now check that community credit classes are displayed in the filter section once activated.

**Comment by erikalogie** [comment]
@flagrede this looks great!

**Review by blushi — APPROVED** [review]
tested and code LGTM

**Review by ryanchristo — APPROVED** [review]
tACK

**Pull request merged**
