### PR TITLE
Create Project Page: Implement Description form

### PR DESCRIPTION
**Pull request by blushi**
## Description

Closes: https://github.com/regen-network/regen-registry/issues/906

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

Go to https://deploy-preview-979--regen-registry.netlify.app/project-pages/3e091856-e73d-11ec-a8de-0267c2be097b/description

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie this is r4r, see "How to test" section in the PR description just above.

**Comment by erikalogie** [comment]
Looks good to me!

**Comment by blushi** [comment]
@haveanicedavid @victordelval this is R4R!

**Review by haveanicedavid — APPROVED** [review]

**Review by victordelval — APPROVED** [review]

**Comment by victordelval** [comment]
@blushi a small detail of style. The steps of the Stepper component are stretched too wide in width... At first I was thinking the form card was too small, but it looks like it's just the Stepper.

image

**Comment by blushi** [comment]
> @blushi a small detail of style. The steps of the Stepper component are stretched too wide in width... At first I was thinking the form card was too small, but it looks like it's just the Stepper.
> 
> image

cc/ @erikalogie do we want to set a max width for the stepper?

**Comment by erikalogie** [comment]
Yes, it should be 800px wide. Good catch victor!

**Comment by blushi** [comment]
it was quite a small change so just added it here

**Comment by blushi** [comment]
@Mergifyio backport redwood hambach

**Pull request merged**
