### PR TITLE
fix: APP-383 align create project button

### PR DESCRIPTION
**Pull request by r41ph**
## Description

https://regennetwork.atlassian.net/browse/APP-383

### Author Checklist
I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1. Check '+ Create project' button is aligned as expected both when users are logged in and not logged in.
 => https://deploy-preview-2568--regen-marketplace.netlify.app/

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
NCT/PROJECTS/STATS menu items are now not centered vertically (a bit too low) image

vs on dev:

image

**Comment by blushi** [comment]
I know this wasn't part of the task, but we should probably also adjust the language switcher position. Now that "create project" is aligned with the menu items on the left, it looks quite bad when user is logged in:
image

Is this a quick fix or should we create another task?

I think the actual issue is that when logged in, the menu items are not centered vertically:

image

**Comment by r41ph** [comment]
> Is this a quick fix or should we create another task?

I think it'd probably be easier to do it in this task. I'll have a quick look and let you know.

**Comment by r41ph** [comment]
@erikalogie @blushi please have a look, I have aligned the language switcher too.

**Comment by erikalogie** [comment]
LGTM!

**Pull request merged**
