### PR TITLE
fix: APP-126 adding multiple files at once to MediaForm gallery photos

### PR DESCRIPTION
**Pull request by blushi**
## Description

https://regennetwork.atlassian.net/browse/APP-126?atlOrigin=eyJpIjoiMmRmM2Q0NzE0YTEwNDU2YmEwMWEwMmQxYWU4ZTczYzUiLCJwIjoiaiJ9

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1. From https://deploy-preview-2357--regen-marketplace.netlify.app/, log in
2. Edit or create a project
3. From the media form, select/drop multiple images at once to the gallery photos and add caption and/or credit
4. Captions/credits should be filled in correctly for all images

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@clevinson @erikalogie see testing instructions

**Comment by erikalogie** [comment]
@blushi 

When I first started testing this, after I upload the photos, they show up with the correct captions on the page but then I get an "error, something went wrong" on clicking the save button. I haven't been able to reproduce this again, so I'm not sure what was going on there.

Also, I realized that we need to have the same popup alert on the "view project" button that we have on the other navigation items for "Are you sure you want to discard your changes?"

Another weird thing that happened is that I clicked the view project button, then went back to my project (which didn't save my changes because of the issue mentioned above), and then I got this error:
Screenshot 2024-05-07 at 9 50 01 AM. There was also some weird stuff going on with the captions where it had prefilled the captions. I haven't been able to reproduce this error again either, so I don't know what is going on here.

**Comment by blushi** [comment]
@erikalogie I believe the issues might be related to the fact that there were no off chain project created yet for this on chain project in the staging database. I'll investigate how to avoid those.

**Comment by blushi** [comment]
@erikalogie this should be fixed now. I've deleted the off chain project for C02-002 so you should be able to test this again in the same testing conditions.

**Comment by erikalogie** [comment]
LGTM @clevinson I think you should test this too

**Review by clevinson — APPROVED** [review]
Tested and works as expected!

**Pull request merged**
