### PR TITLE
Update Create/Edit Project Page, Create Batch and Dashboard routes to be accessible by users connected with Keplr wallet

### PR DESCRIPTION
**Pull request by blushi**
## Description

Closes: https://github.com/regen-network/regen-registry/issues/910

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed
- [ ] once the PR is closed, set up backport PRs for `redwood` and `hambach` (see below)

#### Setting up backport PRs

After merging your PR to `master`, set up backports by doing the following:

1. If your branch does not have merge commits, add the following comment to
   your PR, `@Mergifyio backport redwood hambach`.

2. If your branch does have merge commits:

    a. Pull latest `master`, `hambach` and `redwood` branches

    b. Create new branches for backports and merge `master` (replace `<PR#>` with your PR #)
    ```
    git checkout -b hambach-backport-<PR#> hambach
    git merge master
    git push origin hambach-backport-<PR#>
    git checkout -b redwood-backport-<PR#> redwood
    git merge master
    git push origin redwood-backport-<PR#>`
    ```

    c. Open new PRs in regen-web targeting `hambach` and `redwood`, respectively.
  

### How to test

Test that those routes are only accessible if connected to Keplr (else displays the error banner):
- https://deploy-preview-992--regen-registry.netlify.app/ecocredits/dashboard
- https://deploy-preview-992--regen-registry.netlify.app/ecocredits/create-batch
- https://deploy-preview-992--regen-registry.netlify.app/project-pages/3e091856-e73d-11ec-a8de-0267c2be097b/roles
- https://deploy-preview-992--regen-registry.netlify.app/project-pages/3e091856-e73d-11ec-a8de-0267c2be097b/edit/roles (please ignore the different steps on the left panel which have not been updated yet to the latest project edit flow)

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie Please see testing instructions in the PR description above.

**Comment by erikalogie** [comment]
This appears to be working correctly. Maybe we should have a separate task to display something on the page too as well as the error banner? Something similar to this page: https://www.figma.com/file/yqzXQFW1TaUWC2csqKYhYV/Error-Pages?node-id=70%3A4925. It's not that important right now but if you agree I can add something to the backlog.

**Comment by blushi** [comment]
> This appears to be working correctly. Maybe we should have a separate task to display something on the page too as well as the error banner? Something similar to this page: https://www.figma.com/file/yqzXQFW1TaUWC2csqKYhYV/Error-Pages?node-id=70%3A4925. It's not that important right now but if you agree I can add something to the backlog.

Sounds good to me, let's add a design and a dev tasks for that then, thanks!

**Review by flagrede — APPROVED** [review]
Looks good !
Just a suggestion comment.

**Review by victordelval — APPROVED** [review]
LGTM! Just one question @blushi  why do we use `wallet.shortAddress` to check if wallet is connected, instead of `wallet.address`? I guess it won't matter because shorAddress will always (?) be informed... but the address property is the one that is really valid, right?

**Comment by blushi** [comment]
> LGTM! Just one question @blushi why do we use `wallet.shortAddress` to check if wallet is connected, instead of `wallet.address`? I guess it won't matter because shorAddress will always (?) be informed... but the address property is the one that is really valid, right?

shortAddress is just derived from address, so that doesn't really matter but I agree it'd be cleaner to just use address

**Comment by blushi** [comment]
> LGTM! Just one question @blushi why do we use `wallet.shortAddress` to check if wallet is connected, instead of `wallet.address`? I guess it won't matter because shorAddress will always (?) be informed... but the address property is the one that is really valid, right?

Looking more closely at the code now, it seems best to use `address` indeed since `shortAddress` defaults to "-" if `address` is not defined...
Not sure why this had been set it this way... @mhagel I think you're the one who wrote this initially, any comment on this?

**Pull request merged**
