### PR TITLE
fix:  render photo credit field only for images in EditFileForm

### PR DESCRIPTION
**Pull request by r41ph**
## Description

https://regennetwork.atlassian.net/browse/APP-235

---

### Author Checklist

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1. Create a new post
2. Add a new file:
   * If the file is an image the `Photo Credit ` field should be visible
   * If the file is not an image the `Photo Credit ` field should not be visible

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by r41ph** [comment]
@erikalogie @clevinson see testing instructions

**Review by wgardiner — APPROVED** [review]
Works as expected, I think it would look look better with some left padding. Right now "Photo credit" appears right next to the description
image

**Comment by erikalogie** [comment]
> Works as expected, I think it would look look better with some left padding. Right now "Photo credit" appears right next to the description image

I agree with this

**Comment by r41ph** [comment]
@erikalogie I've added some padding as suggested. Please have a look.

**Comment by erikalogie** [comment]
LGTM

**Pull request merged**
