### PR TITLE
fix: APP-434 include offchain projects to more projects section for terrasos

### PR DESCRIPTION
**Pull request by blushi**
## Description

https://regennetwork.atlassian.net/browse/APP-434

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

From any project page, eg https://deploy-preview-2526--regen-marketplace.netlify.app/project/ee345f38-918b-11ef-8f65-022e215a294f, check out "More Projects" section at the bottom, it should show 3 random projects from https://deploy-preview-2526--regen-marketplace.netlify.app/projects/1 (on staging these are not necessarily all real terrasos projects)

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie @S4mmyb see testing instructions

**Comment by blushi** [comment]
> Looks good! Do we need a separate task to make the project cards here match the ones on the /projects page once the credits available have been added? Or will those changes automatically be reflected in the more projects section?

There might be small adjustments to make but either I'll do it if https://github.com/regen-network/regen-web/pull/2520 gets merged first or @flagrede can do it mine gets merged first.

**Review by wgardiner — APPROVED** [review]
Looks good!

**Review by flagrede — APPROVED** [review]
Looks good!
@blushi I just merged https://github.com/regen-network/regen-web/pull/2520 , for the cards to behave the same as in `/projects` page you just need to add the `creditsChildren` prop (see example here: https://github.com/regen-network/regen-web/blob/dev/web-marketplace/src/pages/Projects/AllProjects/AllProjects.tsx#L283-L292).

**Comment by blushi** [comment]
> Looks good! Do we need a separate task to make the project cards here match the ones on the /projects page once the credits available have been added? Or will those changes automatically be reflected in the more projects section?

I've addressed this here, please have another look @erikalogie

**Comment by erikalogie** [comment]
LGTM

**Pull request merged**
