### PR TITLE
chore: release v1.12.0

### PR DESCRIPTION
**Pull request by ryanchristo**
## Description

This pull request merges the latest changes from `dev` into `main` in preparation for the `v1.12.0` release.

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1. https://deploy-preview-2089--regen-website.netlify.app/
2. https://deploy-preview-2089--regen-marketplace.netlify.app/
3. https://deploy-preview-2089--regen-storybook.netlify.app/

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by ryanchristo** [comment]
Storybook netlify build failed:
- https://github.com/regen-network/regen-web/pull/2089/checks?check_run_id=16590353494

Clearing the cache and rebuilding succeeded:
- https://app.netlify.com/sites/regen-storybook/deploys/64fa2f5137e4fa53fcd12afc

**Comment by blushi** [comment]
> Storybook netlify build failed:
> 
> * https://github.com/regen-network/regen-web/pull/2089/checks?check_run_id=16590353494
> 
> Clearing the cache and rebuilding succeeded:
> 
> * https://app.netlify.com/sites/regen-storybook/deploys/64fa2f5137e4fa53fcd12afc

Side note that this might occur on the production deploy too once this is merged, in which case, we should clear the cache and rebuild too.

**Comment by blushi** [comment]
While testing, I've found some weird behavior in the activity table https://deploy-preview-2089--regen-marketplace.netlify.app/stats/activity
If you go to the third page, then come back to the previous ones, it will still display 2 items from the third page at the top. As you can see on the screenshot, we have 2 txs from 12 days ago on the first page above the most recent txs:

image

cc/ @flagrede @wgwz any idea what could cause that?
Not sure if we should consider this a blocker for the release though.

**Comment by flagrede** [comment]
@blushi This is a weird bug indeed, would need to investigate.

**Comment by flagrede** [comment]
@blushi fixed here: https://github.com/regen-network/regen-web/pull/2095

**Comment by flagrede** [comment]
Will reopen on `dev` as we have fixes to add to the release PR.

**Comment by ryanchristo** [comment]
Ok, I've added the latest commits and the fix @flagrede provided. Ready for another review.

**Comment by ryanchristo** [comment]
We should probably include https://github.com/regen-network/regen-web/pull/2096 though given this would otherwise be a hot fix.

**Comment by ryanchristo** [comment]
cc @blushi @flagrede can you two take another look when you get a chance. :pray:

**Comment by blushi** [comment]
Getting the following error on the marketplace app deploy preview:
```
index-55eed4a2.js:1078 Uncaught TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at requireDecUtils (index-55eed4a2.js:1078:134624)
    at requireCoinUtils (index-55eed4a2.js:1078:135756)
    at requireDecimal (index-55eed4a2.js:1078:139640)
    at requireInt (index-55eed4a2.js:1078:144776)
    at index-55eed4a2.js:1078:134120
```
which is weird because it's not on dev.
I'll try to clear the cache and re-build on netlify.

**Comment by blushi** [comment]
The buffer issue is still there for some stories on storybook: https://deploy-preview-2089--regen-storybook.netlify.app/?path=/story/forms--user-profile but I don't think this is a blocker for the release, can be fixed later.

> Getting the following error on the marketplace app deploy preview:
> 
> ```
> index-55eed4a2.js:1078 Uncaught TypeError: Object.defineProperty called on non-object
>     at Function.defineProperty (<anonymous>)
>     at requireDecUtils (index-55eed4a2.js:1078:134624)
>     at requireCoinUtils (index-55eed4a2.js:1078:135756)
>     at requireDecimal (index-55eed4a2.js:1078:139640)
>     at requireInt (index-55eed4a2.js:1078:144776)
>     at index-55eed4a2.js:1078:134120
> ```
> 
> which is weird because it's not on dev. I'll try to clear the cache and re-build on netlify.

Ok this is working back again now.

**Review by flagrede — APPROVED** [review]

**Pull request merged**
