### PR TITLE
fix: hide program on terrasos in project card

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: APP-496

Hide program in project card for Terrasos.

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by blushi — APPROVED** [review]
utACK

**Comment by flagrede** [comment]
@erikalogie You can check that the program is now hidden on project card here: https://deploy-preview-2561--terrasos.netlify.app/

**Comment by erikalogie** [comment]
Is it also hidden on the credit class card? It's a little hard for me to tell if this is working properly as it is not the same on-chain project as on production

**Comment by flagrede** [comment]
@erikalogie Actually forgot about the credit class card, I just fix that.

**Pull request merged**
