### PR TITLE
feat: APP-81 Hide ecocredits tab or certificates tab on profiles if tab is "hidden" or if user has no Keplr wallet

### PR DESCRIPTION
**Pull request by blushi**
## Description

Needs: https://github.com/regen-network/regen-server/pull/458

https://regennetwork.atlassian.net/browse/APP-81?atlOrigin=eyJpIjoiNzZiMzA2MGUzYmM3NGEwMmFhZWFkZmNhYmRhMjQ5MjgiLCJwIjoiaiJ9

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

- Account without wallet: https://deploy-preview-2333--regen-marketplace.netlify.app/profiles/4ef3dde2-9504-11ee-acf3-0267c2be097b/projects, whole Portfolio tab hidden
- web3 account with ecocredits/basket tokens and certificate tabs: https://deploy-preview-2333--regen-marketplace.netlify.app/profiles/regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46/portfolio
- web3 account with hidden ecocredits/basket tokens tab: https://deploy-preview-2333--regen-marketplace.netlify.app/profiles/regen1gzw5snmgee76r83cxumdgpsn2zht3l7cycu7en
- web3 account with hidden certificates tab and no basket token so this tab gets hidden: https://deploy-preview-2333--regen-marketplace.netlify.app/profiles/regen106ljn6kds9vegaux0w4jnend97fdm50yx6le6y/portfolio
- web3 account with hidden ecocredits/basket tokens and certificate tabs so the whole Portfolio tab gets hidden: https://deploy-preview-2333--regen-marketplace.netlify.app/profiles/regen18xc64ltgtu7uthkpj4fug2dnm8z5m0narvy0ww/projects

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by clevinson** [comment]
Happy to review this, but not 100% sure how to test. I guess we need to wait until https://github.com/regen-network/regen-server/pull/458 is merged before testing? and then manually switching "hide" settings in Postgres?

**Comment by blushi** [comment]
> Happy to review this, but not 100% sure how to test. I guess we need to wait until [regen-network/regen-server#458](https://github.com/regen-network/regen-server/pull/458) is merged before testing? and then manually switching "hide" settings in Postgres?

Yeah I'll add some testing instructions once the server pr is merged and add you as reviewer

**Comment by blushi** [comment]
@erikalogie @clevinson see testing instruction in the PR description

**Review by aaronc — APPROVED** [review]
utACK. Code looks fine but needs testing

**Comment by erikalogie** [comment]
LGTM!

**Pull request merged**
