### PR TITLE
fix: use activeAccount addr in profile link

### PR DESCRIPTION
**Pull request by blushi**
## Description

Closes:  regen-network/rnd-dev-team#1869

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

From https://deploy-preview-2320--regen-marketplace.netlify.app/
1. Log in with Keplr wallet addr A 
2. Switch to wallet addr B from Keplr, and do not accept the "prove ownership" popup, just close it 
3. Copy link to your profile from your profile page, this should have the right addr in it (addr A)

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie see testing instructions

**Comment by erikalogie** [comment]
@blushi this looks good, just noting here that I again had the issue with not seeing all the tabs in the dropdown or on the profile page: 
Screen Shot 2024-03-12 at 9 14 11 AM

This happened while following the steps above:
Uploading screencast 2024-03-12 09-17-32.mp4…

**Comment by blushi** [comment]
> @blushi this looks good, just noting here that I again had the issue with not seeing all the tabs in the dropdown or on the profile page: Screen Shot 2024-03-12 at 9 14 11 AM

Yeah as discussed on slack, I've created a separate issue for that https://github.com/regen-network/regen-web/issues/2322

**Comment by erikalogie** [comment]
> > @blushi this looks good, just noting here that I again had the issue with not seeing all the tabs in the dropdown or on the profile page: Screen Shot 2024-03-12 at 9 14 11 AM
> 
> Yeah as discussed on slack, I've created a separate issue for that #2322

Ok perfect, this is good then!

**Review by aaronc — APPROVED** [review]

**Pull request merged**
