### PR TITLE
feat: adjust spacing project page

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/regen-registry#1770

- consistent spacing in the main and side columns on the project page.
- swap story and details section

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1. https://deploy-preview-2027--regen-marketplace.netlify.app/project/C02-002
2. https://deploy-preview-2027--regen-marketplace.netlify.app/project/C02-009
3. https://deploy-preview-2027--regen-marketplace.netlify.app/project/C01-001

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by ryanchristo — COMMENTED** [review]
Looking good.

The only thing missing from what I can tell is the spacing between certifications and ratings and the concierge card.

Screenshot from 2023-08-16 14-02-40

Also it looks like one image might not have been fully uploaded when opening the issue. Not sure if there was something we are missing or if we can ignore this (cc @erikalogie):

> [Uploading... image.png]

**Comment by flagrede** [comment]
@ryanchristo the spacing between certifications and ratings and the concierge card is 20px (as requested in the issue description). Should it be something else?

**Comment by ryanchristo** [comment]
> Should it be something else?

I'm a bit confused by the request. I'm ok with the current spacing if @erikalogie is.

Deploy preview fixed. @erikalogie can you QA this now.

**Comment by flagrede** [comment]
@ryanchristo spacings for this PR have been adjusted based on @erikalogie comment here: https://github.com/regen-network/regen-web/pull/2028#issuecomment-1682050366

**Comment by erikalogie** [comment]
@flagrede Do you want me to QA the spacing on this PR? I just found one area that could use work on mobile:
https://monosnap.com/file/czYrffzcRgtQljuQ0NQdm97w87p0lj

There are a couple of other things but not sure if you are still working on this

**Comment by erikalogie** [comment]
I still see this spacing on mobile: https://monosnap.com/file/QkOe0Dko8GZE3wPgn1h8gTWpYxMbiS
So I'm not sure if you saw this? 
image

Also there is one very small issue here: https://monosnap.com/file/nEwfs7D7lUe3cWlQRbZdZ9w9LKzQku

**Comment by flagrede** [comment]
@erikalogie I confirm that I didn't see this screenshot, it's probably the one that is not displayed correctly in the issue description. I just made a fix for that.
Regarding the [second issue](https://monosnap.com/file/nEwfs7D7lUe3cWlQRbZdZ9w9LKzQku), I double checked and it's the same spacing (30px on mobile and 40px on desktop). Should I make it smaller in case the `see more` is displayed ?

**Review by ryanchristo — APPROVED** [review]
tACK. The spacing between certifications and ratings is fixed. As far as I can tell, the additional requests (missing image in original issue) have been addressed.

Pre-approving pending last question about spacing adjustment accounting for "see more".

**Comment by erikalogie** [comment]
I think this is good enough

**Pull request merged**
