### PR TITLE
feat:  add new purchase option sell orders column

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/regen-registry#1204

image

add:
- new purchase options column
- new InfoLabel component
- new icons

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed
- [ ] once the PR is closed, set up backport PRs for `redwood` and `hambach` (see below)

#### Setting up backport PRs

After merging your PR to `master`, set up backports by doing the following:

1. If your branch does not have merge commits, add the following comment to
   your PR, `@Mergifyio backport redwood hambach`.

2. If your branch does have merge commits:

    a. Pull latest `master`, `hambach` and `redwood` branches

    b. Create new branches for backports and merge `master` (replace `<PR#>` with your PR #)
    ```
    git checkout -b hambach-backport-<PR#> hambach
    git merge master
    git push origin hambach-backport-<PR#>
    git checkout -b redwood-backport-<PR#> redwood
    git merge master
    git push origin redwood-backport-<PR#>`
    ```

    c. Open new PRs in regen-web targeting `hambach` and `redwood`, respectively.
  

### How to test

1. Go to https://deploy-preview-1260--regen-registry.netlify.app/storefront
2. Check the new column

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie you can check the new column here: https://deploy-preview-1260--regen-registry.netlify.app/storefront

**Comment by erikalogie** [comment]
@flagrede this looks great. 

One thing, which is totally not your fault as I didn't have the link in the task description to the prototype view where you can see this, is that the "tradable" credits should also show the "retired" tag since all tradable credits are also retirable.

You can see this here: https://www.figma.com/proto/seUiQM2SPt78KJiDL0Ea8m/Basic-Ecocredits-Ledger-View-%2F-Marketplace?page-id=2485%3A175084&node-id=2485%3A176845&viewport=5206%2C1244%2C0.5&scaling=scale-down&starting-point-node-id=2485%3A176845&show-proto-sidebar=1.

Sorry about that! Will try to always write good descriptions with all the links in the future.

**Comment by flagrede** [comment]
> @flagrede this looks great.
> 
> One thing, which is totally not your fault as I didn't have the link in the task description to the prototype view where you can see this, is that the "tradable" credits should also show the "retired" tag since all tradable credits are also retirable.
> 
> You can see this here: https://www.figma.com/proto/seUiQM2SPt78KJiDL0Ea8m/Basic-Ecocredits-Ledger-View-%2F-Marketplace?page-id=2485%3A175084&node-id=2485%3A176845&viewport=5206%2C1244%2C0.5&scaling=scale-down&starting-point-node-id=2485%3A176845&show-proto-sidebar=1.
> 
> Sorry about that! Will try to always write good descriptions with all the links in the future.

@erikalogie  Oh make sense.. will change that.

**Comment by flagrede** [comment]
@erikalogie should be updated.

**Comment by erikalogie** [comment]
@flagrede this looks great! One last thing, just change "purchase option" to "purchase options". Would be great if we can get some approvals on this today to merge it because we are doing a marketplace jam later this afternoon to get everyone in the company who hasn't used the marketplace yet to try it out.

**Review by mhagel — APPROVED** [review]
Looks cool!

**Review by victordelval — APPROVED** [review]

**Comment by flagrede** [comment]
@Mergifyio backport redwood hambach

**Pull request merged**
