### PR TITLE
fix: APP-114 edit profile

### PR DESCRIPTION
**Pull request by blushi**
## Description

needs: https://github.com/regen-network/regen-server/pull/466

https://regennetwork.atlassian.net/browse/APP-114?atlOrigin=eyJpIjoiOGE2YzJkZTgzMjE2NDVlNGE3NGUxZjYyMmY0YmI1ZDQiLCJwIjoiaiJ9

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

Log in from https://deploy-preview-2355--regen-marketplace.netlify.app/ and try to edit your profile (profile/background image and another field)
If you have access to s3, also check that when you update an image, the old one gets deleted.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie @clevinson see testing instructions

**Comment by erikalogie** [comment]
This looks good. It would be ideal if the button were greyed out, same as on the project form, when there aren't any changes that need to be saved. I also think we need another issue to have the  "Are you sure you want to discard your changes?" popup appear when the user clicks the "settings" tab because otherwise they could easily forget to save their changes. I know there was some technical reason not to have this "Are you sure" popup come up when they navigate away in any way, but ideally we would implement that as well both for this form, the settings form and the project form. Should I open a new ticket for adding this popup and fixing the button?

**Review by aaronc — APPROVED** [review]
utACK

**Comment by blushi** [comment]
> > > This looks good. It would be ideal if the button were greyed out, same as on the project form, when there aren't any changes that need to be saved. I also think we need another issue to have the "Are you sure you want to discard your changes?" popup appear when the user clicks the "settings" tab because otherwise they could easily forget to save their changes. I know there was some technical reason not to have this "Are you sure" popup come up when they navigate away in any way, but ideally we would implement that as well both for this form, the settings form and the project form. Should I open a new ticket for adding this popup and fixing the button?
> > 
> > 
> > Sure we can even have 2 tickets, one for the popup and one for the button
> 
> Ok, I've opened those: https://regennetwork.atlassian.net/browse/APP-136 and https://regennetwork.atlassian.net/browse/APP-135

@erikalogie looks like APP-136 is for the "view project" button from the project edit forms. It looks like we already display the warning when the user clicks on settings from the edit profile form.

**Pull request merged**
