### PR TITLE
feat: documentation table project page

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/regen-registry#1588

- add a new `DocumentationTable` based on `ActionTable`
- put `DocumentationTable` and `CreditBatchesTable` in `Tabs` container on `ProjectDetails` page

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1. https://deploy-preview-1875--regen-registry.netlify.app/project/C01-001

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie you can have a look at the new documentation table here: https://deploy-preview-1875--regen-registry.netlify.app/project/C01-001

**Comment by flagrede** [comment]
@erikalogie I've handled your feedback and added more documents.

**Comment by erikalogie** [comment]
> @erikalogie I've handled your feedback and added more documents.

Looks great now, thanks!

**Review by wgwz — APPROVED** [review]
utACK, looks great! awesome work

**Pull request merged**
