### PR TITLE
feat: hide old gallery photos

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: 
regen-network/regen-registry#1641
regen-network/regen-registry#1111

- remove gallery photos from the ProjectDetails media header
- clean code related to using gallery photos

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1. https://deploy-preview-1870--regen-registry.netlify.app/project/C01-001

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie you can check that we no longer display gallery photos in the header here: https://deploy-preview-1870--regen-registry.netlify.app/project/C01-001

**Comment by flagrede** [comment]
@erikalogie I've updated the PR to also fix this issue: https://app.zenhub.com/workspaces/regen-registry-5f8998bec8958d000f4609e2/issues/gh/regen-network/regen-registry/1111

**Comment by erikalogie** [comment]
@flagrede looks good, just a couple of small comment on spacing: https://monosnap.com/file/N82d9PnHSWzYfneaSxWIZgwu3OXW91

**Comment by flagrede** [comment]
@erikalogie should be better for the spacing.

**Comment by erikalogie** [comment]
> @erikalogie should be better for the spacing.

Looks good now!

**Pull request merged**
