### PR TITLE
feat: APP-25 post page

### PR DESCRIPTION
**Pull request by blushi**
## Description

https://regennetwork.atlassian.net/browse/APP-25?atlOrigin=eyJpIjoiMDcyYzVhOTBiZmZiNGZkODljMjk4NGJmMThmZGIxMjYiLCJwIjoiaiJ9
closes: #2225

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

- Public, no files, timeline with signed events: https://deploy-preview-2384--regen-marketplace.netlify.app/post/regen:13toVhd6kXzoVJ43rZw7baajAzAj9W4W5tVnaysv5mvyYDhgGaFSD1F.rdf
- Public with files: https://deploy-preview-2384--regen-marketplace.netlify.app/post/regen:13toVgXGrGiGGYDsAfeRZJUmC484QH61gshtZLWSqsHYjfq7oesrTi3.rdf
- Private files locations: https://deploy-preview-2384--regen-marketplace.netlify.app/post/regen:13toVgpnFSEGah5qgrmF6sfX1dhYfwSeWCA275JyFUSzqYjSCLxTAUT.rdf
- Private files: https://deploy-preview-2384--regen-marketplace.netlify.app/post/regen:13toVguQZphD4zNDo3BUJWSCZe16UByR7X58jxKKnRG13ob663GgRba.rdf
- Private post: https://deploy-preview-2384--regen-marketplace.netlify.app/post/regen:13toVgN9DezCJQdiPdwjXoi26FdNrK2x3coMM7h5nkJGxTqT6KnievS.rdf
- To test the admin views, it'd be good to have the full flow implemented first so you can easily access your created posts. These views are already partially available from storybook: https://regen-storybook.netlify.app/?path=/story/organisms-postfiles--private-locations-as-admin and https://regen-storybook.netlify.app/?path=/story/organisms-postfiles--private-files-as-admin (missing: https://www.figma.com/design/Bksz1JeDYxQVIXdI46EgPT/Project-Posts?node-id=1154-66029&m=dev)

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@clevinson see testing instructions

**Comment by blushi** [comment]
@erikalogie see testing instructions

**Review by aaronc — APPROVED** [review]

**Comment by clevinson** [comment]
Looks great!

There's a few behaviors that I think would be nice to change / improve:
1. When clicking on the files on a [post page with map view](https://deploy-preview-2384--regen-marketplace.netlify.app/post/regen:13toVgXGrGiGGYDsAfeRZJUmC484QH61gshtZLWSqsHYjfq7oesrTi3.rdf), my entire webpage scrolls up and down as the map view resizes and centers on the file. I don't have an issue with the map view adjusting if the file is not in full view, but I don't think the parent div / page should have to scroll as well.
2. When scrolling through the page, if my cursor is on the map then it triggers a map zoom instead of a page scroll. Since the map covers a large portion of hte page, I think it might be quite common for the user to have their cursor on the map and they want to scroll the page instead of zooming in. Personally I think we can just disable scroll-to-zoom on the map view, and users can click the +/- buttons in the top left if they really want to zoom on the map? Curious what @erikalogie thinks about this
3. The "Next" and "Previous" buttons at the bottom don't seem to work on any of the testing post pages. I think they probably shouldn't be present if we don't have an actual next or previous post page to link to.

**Comment by erikalogie** [comment]
> Looks great!
> 
> There's a few behaviors that I think would be nice to change / improve:
> 
> 1. When clicking on the files on a [post page with map view](https://deploy-preview-2384--regen-marketplace.netlify.app/post/regen:13toVgXGrGiGGYDsAfeRZJUmC484QH61gshtZLWSqsHYjfq7oesrTi3.rdf), my entire webpage scrolls up and down as the map view resizes and centers on the file. I don't have an issue with the map view adjusting if the file is not in full view, but I don't think the parent div / page should have to scroll as well.

Agree the webpage should not move. I do, however, think it would be ideal if we could avoid the need to adjust the map view too. For example, look at the search results map on Airbnb. They position the popup windows such that it is not necessary to change the map view. Not sure of the difficulty of implenting such a thing, but the end result is very smooth.

https://github.com/regen-network/regen-web/assets/8460237/9f5aed8c-908c-4475-8404-da1f6af4cd75


> 2. When scrolling through the page, if my cursor is on the map then it triggers a map zoom instead of a page scroll. Since the map covers a large portion of hte page, I think it might be quite common for the user to have their cursor on the map and they want to scroll the page instead of zooming in. Personally I think we can just disable scroll-to-zoom on the map view, and users can click the +/- buttons in the top left if they really want to zoom on the map? Curious what @erikalogie thinks about this

Yes, I agree with this, this is also what Airbnb does with the map on the listing pages

> 3. The "Next" and "Previous" buttons at the bottom don't seem to work on any of the testing post pages. I think they probably shouldn't be present if we don't have an actual next or previous post page to link to.

Agreed.

**Comment by erikalogie** [comment]
Some further feedback:
1) Alignment here looks a little weird: https://monosnap.com/file/gInQFXAp4eDdhOgHVhzTjeW2ojhsRz. This looks worse on mobile because of the alignment issue between the "created by" and the author's name: https://monosnap.com/file/tyRXamleTAfsQaOoCc9EvipFpUVZnN
2) Spacing for "files available on request" tag looks too large: https://monosnap.com/file/lTxAqL57c34JA7qdQ40HgexrT3D1ma

**Comment by blushi** [comment]
> The "Next" and "Previous" buttons at the bottom don't seem to work on any of the testing post pages. I think they probably shouldn't be present if we don't have an actual next or previous post page to link to.

This isn't implemented yet, as I would need some code from this other PR: https://github.com/regen-network/regen-web/pull/2390 so once this PR is merged, I'll make the prev/next buttons functional here to avoid duplicating codes throughout multiple PRs which can result in conflicts.

**Comment by blushi** [comment]
@erikalogie @clevinson ready for another look

**Comment by erikalogie** [comment]
This looks good now! Nice work!

**Pull request merged**
