### PR TITLE
feat: APP-150 add featured projects sorting on /projects page

### PR DESCRIPTION
**Pull request by blushi**
## Description

https://regennetwork.atlassian.net/browse/APP-150?atlOrigin=eyJpIjoiMjAwOGNjZThhMjc3NGQ1Zjk3ZTg2NmJiMTNmY2ViMWIiLCJwIjoiaiJ9

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

From https://deploy-preview-2387--regen-marketplace.netlify.app/projects/1, check that the featured projects set on sanity (https://regen.sanity.studio/staging/structure/registry;home) appear first, then the projects from price low to high.
Since "community projects" filter were off by default, if any of the featured projects is a community project, it won't appear first when featured projects sorting is enabled. After some discussions with @clevinson we've decided that we could simply turn on this community projects filter by default for now (since there's no community projects on prod yet), have it set as an environment variable that we could easily turn off again if we want in the future.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie @clevinson see testing instructions

**Review by aaronc — APPROVED** [review]
utACK

**Review by clevinson — APPROVED** [review]
Approving as I think the issue that I had in testing was caused by something to do with CORS restrictions.

On this deploy preview I'm only able to see the first two projects in the "featured" list at the top of the projects page.  The 3rd and 4th projects that are listed as featured in Sanity do not show at all. Is this because of some CORS issue? It would be great if we can find a way to resolve this as it's difficult to do user testing when sometimes resources don't load on deploy previews.

The two projects that should render (since they are in the Sanity featured projects list):
- http://dev.app.regen.network/project/3f27f250-3bab-11eb-99d4-0267c2be097b
- http://dev.app.regen.network/project/prefinance-project

Note how both of these projects give 404's on the deploy preview:
- https://deploy-preview-2387--regen-marketplace.netlify.app/project/3f27f250-3bab-11eb-99d4-0267c2be097b
- https://deploy-preview-2387--regen-marketplace.netlify.app/project/prefinance-project

**Comment by blushi** [comment]
> The two projects that should render (since they are in the Sanity featured projects list):
> 
> http://dev.app.regen.network/project/3f27f250-3bab-11eb-99d4-0267c2be097b
> http://dev.app.regen.network/project/prefinance-project
> Note how both of these projects give 404's on the deploy preview:
> 
> https://deploy-preview-2387--regen-marketplace.netlify.app/project/3f27f250-3bab-11eb-99d4-0267c2be097b
> https://deploy-preview-2387--regen-marketplace.netlify.app/project/prefinance-project

This is happening from Safari, right? This isn't a CORS issue, this is because Safari doesn't include third party cookies by default. In order to make it work, you should go to Safari Preferences, then Privacy panel and make sure "Prevent cross-site tracking" and "Block all cookies" are both unchecked.

**Pull request merged**
