### PR TITLE
feat: add community projects filter

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/regen-registry#1087

- add a filter on `/projects` page to filter community projects
- adapt filter/sort layout to mobile
- add boolean `hasCommunityProjects` and flag `useCommunityProjects` in `useProjectsWithOrders`
- remove old fetching hook `useProjectsSellOrders`

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1. https://deploy-preview-1934--regen-registry.netlify.app/projects/1

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie You can test the community filter flag here: https://deploy-preview-1934--regen-registry.netlify.app/projects/1

**Comment by erikalogie** [comment]
@flagrede this looks good to me! The only thing is the "learn more in our docs" link I don't believe is correct. @ryanchristo @clevinson where will the explanation of how to administer community credits live? We need a link in order to complete this task.

**Review by blushi — APPROVED** [review]
tACK

**Comment by ryanchristo** [comment]
> The only thing is the "learn more in our docs" link I don't believe is correct. @ryanchristo @clevinson where will the explanation of how to administer community credits live? We need a link in order to complete this task.

I think the link is ok for now but we will need to update once we have more official documentation. I'm not sure we know yet where exactly that documentation will live but I'm guessing this is related to the CLI tutorial we are planning to write, so the link would eventually be something like the following: https://docs.regen.network/tutorials/user/credit-class-administration.html

**Comment by flagrede** [comment]
@ryanchristo thanks for the info, I guess I can update the link to `https://docs.regen.network/tutorials/` in the meantime.

**Pull request merged**
