### PR TITLE
feat: APP-136 show warning when clicking "view project" from project edit with unsaved changes

### PR DESCRIPTION
**Pull request by blushi**
## Description

https://regennetwork.atlassian.net/browse/APP-136?atlOrigin=eyJpIjoiYzIwZDZmZDVlYzg3NDhiMzk5ZTAxNjdmNmViNmJjYmYiLCJwIjoiaiJ9

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1. From https://deploy-preview-2363--regen-marketplace.netlify.app/, log in and edit a published project (not a draft)
2. Make some changes without saving and click "view project"
3. Click "cancel" to stay on the form or "yes, delete" to go to the project page without saving

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie @clevinson see testing instructions

**Comment by clevinson** [comment]
Just tested! Generally looks good. 3 small requests:
1. I think when clicking on a hyperlink in the header we should also show this prompt.  Currently, it only shows the prompt when clicking "View Project" or navigating to a different tab on the edit project page
2. The copy in the discard changes modal should be updated to:
  a. "If you proceed, you will lose all the changes you made. This cannot be undone." => "If you proceed, you will lose all unsaved changes you made. This cannot be undone."
  b. "Yes, Delete" button should say "Yes, Discard"
3. On the first time the discard modal loads, the modal quickly changes height (in a reactive way) when the bumble bee image loads. Can we preset the modal to pad based on the expected image height? This way the total modal height would not change if the icon is taking more time to load than the modal text?

**Review by clevinson — COMMENTED** [review]
Just tested! Generally looks good. 3 small requests:
1. I think when clicking on a hyperlink in the header we should also show this prompt.  Currently, it only shows the prompt when clicking "View Project" or navigating to a different tab on the edit project page
2. The copy in the discard changes modal should be updated to:
  a. "If you proceed, you will lose all the changes you made. This cannot be undone." => "If you proceed, you will lose all unsaved changes you made. This cannot be undone."
  b. "Yes, Delete" button should say "Yes, Discard"
3. On the first time the discard modal loads, the modal quickly changes height (in a reactive way) when the bumble bee image loads. Can we preset the modal to pad based on the expected image height? This way the total modal height would not change if the icon is taking more time to load than the modal text?

**Comment by erikalogie** [comment]
> Just tested! Generally looks good. 3 small requests:
> 
> 1. I think when clicking on a hyperlink in the header we should also show this prompt.  Currently, it only shows the prompt when clicking "View Project" or navigating to a different tab on the edit project page

I believe there was some technical reason why this was super complicated that we didn't implement it this way for all popups like this originally. @blushi can elaborate.

> 2. The copy in the discard changes modal should be updated to:
>    a. "If you proceed, you will lose all the changes you made. This cannot be undone." => "If you proceed, you will lose all unsaved changes you made. This cannot be undone."
>    b. "Yes, Delete" button should say "Yes, Discard"

I like these recommendations

> 3. On the first time the discard modal loads, the modal quickly changes height (in a reactive way) when the bumble bee image loads. Can we preset the modal to pad based on the expected image height? This way the total modal height would not change if the icon is taking more time to load than the modal text?

Great idea!

**Comment by blushi** [comment]
> > Just tested! Generally looks good. 3 small requests:
> > 
> > 1. I think when clicking on a hyperlink in the header we should also show this prompt.  Currently, it only shows the prompt when clicking "View Project" or navigating to a different tab on the edit project page
> 
> I believe there was some technical reason why this was super complicated that we didn't implement it this way for all popups like this originally. @blushi can elaborate.

More than the complexity, it's actually the impact on the app performance that such a change would have that refrained us from implementing this originally, because this means we would need to listen to any route changes, see previous discussions about this (in the context of the profile edit form): https://github.com/regen-network/regen-web/pull/2144#issuecomment-1737006845
> 
> > 2. The copy in the discard changes modal should be updated to:
> >    a. "If you proceed, you will lose all the changes you made. This cannot be undone." => "If you proceed, you will lose all unsaved changes you made. This cannot be undone."
> >    b. "Yes, Delete" button should say "Yes, Discard"
> 
> I like these recommendations
> 
> > 3. On the first time the discard modal loads, the modal quickly changes height (in a reactive way) when the bumble bee image loads. Can we preset the modal to pad based on the expected image height? This way the total modal height would not change if the icon is taking more time to load than the modal text?
> 
> Great idea!

I'll implement 2. and 3.

**Comment by blushi** [comment]
@clevinson @erikalogie 2. and 3 should be addressed.

@clevinson FYI for updating with the `dev` branch, we use `rebase` instead of `merge` so I've overwritten your merge commit and rebased.

**Review by aaronc — APPROVED** [review]
utACK

**Comment by blushi** [comment]
@clevinson @erikalogie could you test this again please?

**Comment by erikalogie** [comment]
LGTM!

**Review by clevinson — APPROVED** [review]

**Pull request merged**
