### PR TITLE
fix: project card title height

### PR DESCRIPTION
**Pull request by blushi**
## Description

Closes: regen-network/rnd-dev-team#1807

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

Testing on desktop:

https://deploy-preview-2163--regen-marketplace.netlify.app/projects/3 On this particular page, all titles take only one line so the location is moved higher everywhere
On https://deploy-preview-2163--regen-marketplace.netlify.app/projects/2, the first row of projects has at least one project title with 2 lines so the locations in this row are moved down so they all align, while the second row has projects titles with 1 line so the location is just displayed right below the title without any additional space.
This behavior can also be tested from the "More Projects" on individual project pages.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie see testing instructions above

**Review by flagrede — APPROVED** [review]
tACK

**Comment by erikalogie** [comment]
I would have eliminated the space between the header and location everywhere the project name only takes up one line, but this is also ok.

**Comment by blushi** [comment]
> I would have eliminated the space between the header and location everywhere the project name only takes up one line, but this is also ok.

Ok this should be like this now, with some space between the location and the separator when applicable so separators are always aligned.

**Comment by erikalogie** [comment]
@blushi looks great

**Pull request merged**
