### PR TITLE
refactor: rename web-registry to web-marketplace

### PR DESCRIPTION
**Pull request by wgwz**
## Description

Closes: https://github.com/regen-network/regen-web/issues/2009

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by ryanchristo — APPROVED** [review]
tACK. Seems to be running locally with no problem. Any idea what's going on with netlify? I tried clearing the cache and rebuilding but looks like it's still having issues.

**Comment by ryanchristo** [comment]
Ah, right, we have the build path set to `web-registry/build`

**Comment by wgwz** [comment]
@ryanchristo thanks for testing, ya, it's just build directory setting that's the issue.
i was most worried about this commit in this PR:
https://github.com/regen-network/regen-web/pull/2013/commits/1a58e2fa9c69470f4e371c8d7f0b44878ebc9f6b

It was tedious to find all the places that we are using the server endpoints.
Glad to hear the testing looks good on your side though.

Maybe I can fix the merge conflicts and we can get this into dev today?
It's gonna keep picking up merge conflicts otherwise.

Also heads up, when y'all pull this code into your local env's be careful not to lose your `web-registry/.env` file (/cc @flagrede and @blushi ).
That happened to me and it's annoying to have to set that up again.

**Comment by ryanchristo** [comment]
Yea, I think we should get this in sooner than later. As far as I could tell, all the api endpoints were working. Worst case is we catch one we missed in the staging environment

**Pull request merged**
