### PR TITLE
fix: improve MetaDetail layout

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: APP-476

Improve `MetaDetail` layout.

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie @S4mmyb You can check the update of the metadata formatting here: https://deploy-preview-2558--terrasos.netlify.app/project/test-terrasos-project

**Review by blushi — APPROVED** [review]
LGTM

**Comment by erikalogie** [comment]
It looks great, just a couple of tweaks on mobile:
Monosnap Aguadulce Habitat Bank | Terrasos 2024-11-26 08-48-28
Monosnap Aguadulce Habitat Bank | Terrasos 2024-11-26 08-49-34

**Comment by flagrede** [comment]
@erikalogie There was a spacing left on last for list, should be fixed now.

**Comment by erikalogie** [comment]
LGTM

**Pull request merged**
