### PR TITLE
feat: add credit class card to project details

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/regen-registry#1061

- Add credit class card to project page
- Modify CreditClassCard to accept React component for title/description in order to handle sanity content
---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed
- [ ] once the PR is closed, set up backport PRs for `redwood` and `hambach` (see below)

#### Setting up backport PRs

After merging your PR to `master`, set up backports by doing the following:

1. If your branch does not have merge commits, add the following comment to
   your PR, `@Mergifyio backport redwood hambach`.

2. If your branch does have merge commits:

    a. Pull latest `master`, `hambach` and `redwood` branches

    b. Create new branches for backports and merge `master` (replace `<PR#>` with your PR #)
    ```
    git checkout -b hambach-backport-<PR#> hambach
    git merge master
    git push origin hambach-backport-<PR#>
    git checkout -b redwood-backport-<PR#> redwood
    git merge master
    git push origin redwood-backport-<PR#>`
    ```

    c. Open new PRs in regen-web targeting `hambach` and `redwood`, respectively.
  

### How to test

1. Go to https://deploy-preview-1177--regen-registry.netlify.app/projects/C01-001

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
Hey @erikalogie you should be able to see the credit class card on the project page now: https://deploy-preview-1177--regen-registry.netlify.app/projects/C01-001
In the header I only removed the credit class one, let me know if I should also remove methodology and registry.

**Comment by erikalogie** [comment]
Ok this looks good.

Here are some small design comments for desktop: https://monosnap.com/file/7zO9H4eF3PxycPAzKFGHmby3valfam. 
Change top and bottom spacing on mobile: https://monosnap.com/file/ZOsYF1mEL91bqS6p6PjEi5Nc9KFVr2

In the header you can remove the registry as well. Moving the methodology is part of [#1120](https://app.zenhub.com/workspaces/regen-registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-registry/1120)

**Review by haveanicedavid — APPROVED** [review]
👍

**Review by mhagel — APPROVED** [review]

**Comment by flagrede** [comment]
@Mergifyio backport redwood hambach

**Pull request merged**
