### PR TITLE
feat: handle profile without address

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/regen-registry#2076

- rename `/ecocredits` to `/profile`
- rename `/ecocredits/accounts/:accountAddress` to `/profiles?:accountAddressOrId`
- allow public profile to be displayed with a `partyId`
- use party to get address whenever available

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1. Private profile: https://deploy-preview-2086--regen-marketplace.netlify.app/profile/portfolio
2. Public profile with address: https://deploy-preview-2086--regen-marketplace.netlify.app/profiles/regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46/portfolio
3. Public profile with party id (party id of address above): https://deploy-preview-2086--regen-marketplace.netlify.app/profiles/dde9835e-c4b1-11ed-bfb6-0267c2be097b/portfolio
4. Unknown party id: https://deploy-preview-2086--regen-marketplace.netlify.app/profiles/some-id/portfolio

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie you can check the updated profile URLs in the description.

One question, Should we display a different design whenever going to a profile that does not exit, or is it fine like it is now (fourth link)?

**Comment by flagrede** [comment]
@erikalogie ok, let's do that as a follow-up task then for the not found profile case.
You're right about the tabs, this was an issue, I just fixed it.

**Comment by erikalogie** [comment]
great!

**Review by wgwz — APPROVED** [review]
utACK

**Comment by blushi** [comment]
As asked by @erikalogie on figma, see this thread: https://www.figma.com/file/Sb9BavGvlCFPQFpjdDlwsL?node-id=5:2390&mode=dev#549645893, I'm not sure if we want to display the party uuid on the profile page. Some other proposals:

> I think we should just hide it, this is an internal reference in our back-end that is not really useful to display, especially truncated.
> But that makes me think that if you want to share your own profile, then we should probably have a separate button to copy the sharable profile link.
> The other solution would be that instead of using /profile for your own profile, we would just use the same url as for the public profiles, ie /profiles/{id or address} and this way the user could copy/paste the url directly.
> In this case, we would need to adjust our code logic because right now, there are really two distinct pages (user own profile when logged in vs public profiles).

**Comment by flagrede** [comment]
@blushi Ok I hid the user `uuid` for now. We can do a follow-up task for the rest while we figure out exactly what we want.

**Pull request merged**
