### PR TITLE
Release v1.11.0

### PR DESCRIPTION
**Pull request by wgwz**
## Description

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by ryanchristo** [comment]
Would be nice to squeeze in #2002 and #2006. The changes required in #2002 are outside the repo and we should make sure analytics is working again with this release.

**Comment by ryanchristo** [comment]
@blushi would you be ok with merging the pull request (#2002) but keeping the issue open?

**Comment by wgwz** [comment]
that’s fine, i was just opening this, we can definitely add whatever we
need still

**Comment by blushi** [comment]
> @blushi would you be ok with merging the pull request (#2002) but keeping the issue open?

sounds good, I've updated the PR description to be "part of #2002" instead of "closes #2022" and added a checklist in #2022 to better track the remaining changes

**Review by ryanchristo — APPROVED** [review]
LGTM. Pre-approving with the addition of https://github.com/regen-network/regen-web/pull/2017. :pray:

**Pull request merged**
