### PR TITLE
fix: APP-528 registered credits in compliance credits tab

### PR DESCRIPTION
**Pull request by blushi**
## Description

https://regennetwork.atlassian.net/browse/APP-528

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@S4mmyb @erikalogie you can test that on https://deploy-preview-2569--terrasos.netlify.app/project/test-terrasos-project

**Comment by erikalogie** [comment]
LGTM

**Comment by S4mmyb** [comment]
Thanks for the quick turnaround @blushi! Is the logic here that registered amount = tradeable + retired? Or do we pull the registered amount directly from sanity

**Comment by blushi** [comment]
> Thanks for the quick turnaround @blushi! Is the logic here that registered amount = tradeable + retired? Or do we pull the registered amount directly from sanity

The logic was still the one used for regular on chain credits where we display tradable + retired as "Credits issued"
But this doesn't seem to apply to registered compliance credits so now we just display the registered amount from sanity directly

**Pull request merged**
