### PR TITLE
feat: APP-194 add prev/next post functionality

### PR DESCRIPTION
**Pull request by blushi**
## Description

https://regennetwork.atlassian.net/browse/APP-194?atlOrigin=eyJpIjoiNzM5NzkzNmI1M2VkNDI2Zjg0ZjFmZDA1YjE1MWIxNmUiLCJwIjoiaiJ9

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

https://deploy-preview-2398--regen-marketplace.netlify.app

1. Navigate through posts for a project using prev/next buttons, from https://deploy-preview-2398--regen-marketplace.netlify.app/post/regen:13toVgkbviJfqjXYKLoqWt4WAigAYXLLjvYBB1wxB4uoukNM9LVVXT3.rdf. You shouldn't see any private posts.
2. Log in and access one of your post page, you should be able to navigate to a private post using prev or next button.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie see testing instructions

**Comment by erikalogie** [comment]
When I'm on [this page](https://deploy-preview-2398--regen-marketplace.netlify.app/post/regen:13toVgCteum6EuinM8WxCajJb4xijokJ52g4Ayd7yapsajam83Zx6op.rdf) and click the "back" button I get this error
Screenshot 2024-07-18 at 10 36 53 AM

**Comment by blushi** [comment]
> When I'm on [this page](https://deploy-preview-2398--regen-marketplace.netlify.app/post/regen:13toVgCteum6EuinM8WxCajJb4xijokJ52g4Ayd7yapsajam83Zx6op.rdf) and click the "back" button I get this error Screenshot 2024-07-18 at 10 36 53 AM

Looks like the post has been deleted since you tested so I get 404. I've identified somewhere in the code that could fix this. Could you test again with some other posts?

**Comment by erikalogie** [comment]
I'm noticing a few things:
1) The location of the next button should not change even if there is no previous
Regen Marketplace 2024-07-30 09-20-47
2) If I'm on this post for example from 2023, and hit next, I go to the most recent post of 2024, instead of the oldest post from 2024, which would be the next post in chronological order: https://deploy-preview-2398--regen-marketplace.netlify.app/post/regen:13toVhd6kXzoVJ43rZw7baajAzAj9W4W5tVnaysv5mvyYDhgGaFSD1F.rdf
3) If I'm on this page, I can navigate to a post that has been deleted, which shouldn't be the case: https://deploy-preview-2398--regen-marketplace.netlify.app/project/kasigau

**Comment by blushi** [comment]
> 1) The location of the next button should not change even if there is no previous

Fixed.

> 2) If I'm on this post for example from 2023, and hit next, I go to the most recent post of 2024, instead of the oldest post from 2024, which would be the next post in chronological order: https://deploy-preview-2398--regen-marketplace.netlify.app/post/regen:13toVhd6kXzoVJ43rZw7baajAzAj9W4W5tVnaysv5mvyYDhgGaFSD1F.rdf 

This will require a fix at the server side I believe, will let you know once that's done.

> 3) If I'm on this page, I can navigate to a post that has been deleted, which shouldn't be the case: https://deploy-preview-2398--regen-marketplace.netlify.app/project/kasigau

How do you know the post has been deleted? The fact that it doesn't appear on the timeline is because I've changed our API and we need to merge https://github.com/regen-network/regen-web/pull/2409 first for the timeline to work normally

**Comment by blushi** [comment]
> > 3\. If I'm on this post for example from 2023, and hit next, I go to the most recent post of 2024, instead of the oldest post from 2024, which would be the next post in chronological order: https://deploy-preview-2398--regen-marketplace.netlify.app/post/regen:13toVhd6kXzoVJ43rZw7baajAzAj9W4W5tVnaysv5mvyYDhgGaFSD1F.rdf
> 
> This will require a fix at the server side I believe, will let you know once that's done.

Ready to test

**Comment by erikalogie** [comment]
> this page

LGTM

**Comment by erikalogie** [comment]
> > > 3. If I'm on this post for example from 2023, and hit next, I go to the most recent post of 2024, instead of the oldest post from 2024, which would be the next post in chronological order: https://deploy-preview-2398--regen-marketplace.netlify.app/post/regen:13toVhd6kXzoVJ43rZw7baajAzAj9W4W5tVnaysv5mvyYDhgGaFSD1F.rdf
> > 
> > 
> > This will require a fix at the server side I believe, will let you know once that's done.
> 
> Ready to test

LGTM

**Comment by erikalogie** [comment]
One new issue I did spot in testing just now on this project's data stream: https://deploy-preview-2398--regen-marketplace.netlify.app/project/kasigau, is that you can click previous and go to posts that do not appear on the data stream itself. Sending you a video via slack as it is not uploading to github.

**Comment by blushi** [comment]
@erikalogie could you test this again?

**Review by r41ph — APPROVED** [review]

**Pull request merged**
