### PR TITLE
feat: update registry navigation in production

### PR DESCRIPTION
**Pull request by victordelval**
## Description

Closes: regen-network/regen-registry#1274

* Remove legacy menu items and mainnet flag

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed
- [ ] once the PR is closed, set up backport PRs for `redwood` and `hambach` (see below)

#### Setting up backport PRs

After merging your PR to `master`, set up backports by doing the following:

1. If your branch does not have merge commits, add the following comment to
   your PR, `@Mergifyio backport redwood hambach`.

2. If your branch does have merge commits:

    a. Pull latest `master`, `hambach` and `redwood` branches

    b. Create new branches for backports and merge `master` (replace `<PR#>` with your PR #)
    ```
    git checkout -b hambach-backport-<PR#> hambach
    git merge master
    git push origin hambach-backport-<PR#>
    git checkout -b redwood-backport-<PR#> redwood
    git merge master
    git push origin redwood-backport-<PR#>`
    ```

    c. Open new PRs in regen-web targeting `hambach` and `redwood`, respectively.
  

### How to test

1. Go to: https://deploy-preview-1342--regen-registry.netlify.app/

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by victordelval** [comment]
Erika, you can check this now. Now the same navigation menu is displayed on Mainnet or Testnet. Thanks!

**Review by flagrede — APPROVED** [review]
Nice cleanup 🧹

**Comment by erikalogie** [comment]
Looks good, I'm assuming this won't be a problem on production? https://monosnap.com/file/36WjHE5tgXK95QAmoDPONuqaHV72Eb

**Review by wgwz — APPROVED** [review]

**Comment by victordelval** [comment]
@erikalogie I'm not sure what you mean.. In any case the link to the deploy preview was not correct, sorry

https://deploy-preview-1342--regen-registry.netlify.app/

**Comment by victordelval** [comment]
@Mergifyio backport redwood hambach

**Pull request merged**
