### PR TITLE
fix: login on keplr mobile

### PR DESCRIPTION
**Pull request by blushi**
## Description

Closes: #1862
Closes: #1863

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by flagrede — APPROVED** [review]
Nice job on finding this.
I could not test since the preview is on Redwood, I will give it a try once released.

**Review by wgwz — APPROVED** [review]

**Comment by flagrede** [comment]
@blushi I just checked, and the issue is still there unfortunately.

**Comment by blushi** [comment]
yeah looking into it, it seems like somehow `isConnected` is still false, therefore we still display the login button

**Comment by blushi** [comment]
I'm not sure how to clear the cache from Keplr mobile browser so I just deleted Keplr app and reinstalled it to get rid of the cache and it's working again so this confirms it's due to the above.

IMG_2101

will look into a fix for that.

**Pull request merged**
