### PR TITLE
chore: APP-40 social icons updates

### PR DESCRIPTION
**Pull request by blushi**
## Description

https://regennetwork.atlassian.net/browse/APP-40?atlOrigin=eyJpIjoiMzZmNWFiNDRhOWE3NDI0NjlmMTNmYzBhYmNmM2MzZDUiLCJwIjoiaiJ9

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1. Check out footer both on https://deploy-preview-2349--regen-marketplace.netlify.app/ and https://deploy-preview-2349--regen-website.netlify.app/
2. From https://deploy-preview-2349--regen-marketplace.netlify.app/, log in and add a twitter link to your profile and check the X icon is being used on your profile page, as on https://deploy-preview-2349--regen-marketplace.netlify.app/profiles/regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46/portfolio
3. Check out "Connect with us" section on https://deploy-preview-2349--regen-website.netlify.app/press-kit

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie see testing instructions

**Comment by erikalogie** [comment]
@blushi this looks good! Wdyt if I removed the word "Hylo" from their logo? It is the least recognizable of the logos, so maybe best to leave it, but visually it looks a bit weird that it is the only one with the name of the company on it.

**Comment by blushi** [comment]
> @blushi this looks good! Wdyt if I removed the word "Hylo" from their logo? It is the least recognizable of the logos, so maybe best to leave it, but visually it looks a bit weird that it is the only one with the name of the company on it.

Agreed, I can remove it myself!

**Comment by blushi** [comment]
> @blushi this looks good! Wdyt if I removed the word "Hylo" from their logo? It is the least recognizable of the logos, so maybe best to leave it, but visually it looks a bit weird that it is the only one with the name of the company on it.

Agreed, I can update with the updated logo.

**Review by aaronc — APPROVED** [review]
utACK

**Comment by blushi** [comment]
@erikalogie I've updated the hylo logo

**Pull request merged**
