### PR TITLE
feat: APP-155 update VideoInput to detect valid url and display error

### PR DESCRIPTION
**Pull request by blushi**
## Description

https://regennetwork.atlassian.net/browse/APP-155?atlOrigin=eyJpIjoiZWRiMmI2YWY3MzU2NDgzOGFiYTg0NzczNmJkZGQ1OGUiLCJwIjoiaiJ9

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

From https://deploy-preview-2385--regen-marketplace.netlify.app/, go to a project media form and add a video:
- as soon as a valid video url is entered, it will set the form value and show the preview
- if an invalid url is entered, an error message is displayed under the video field. If the user types enter or navigates away with an invalid url, the error should also appear in a red banner at the top.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@clevinson @erikalogie see testing instructions

**Review by aaronc — APPROVED** [review]
utACK

**Review by clevinson — APPROVED** [review]
tACK

**Comment by erikalogie** [comment]
This looks great, but it would be also nice to have the hint in the paragraph with a link to this video plugin's documentation on github (I can't find the link but I know you sent that to me before @blushi). In the mocks the paragraph text reads "Supported types include: YouTube, Facebook, Vimeo, Twitch, and DailyMotion. View the complete list of support videos»"

**Comment by blushi** [comment]
> This looks great, but it would be also nice to have the hint in the paragraph with a link to this video plugin's documentation on github (I can't find the link but I know you sent that to me before @blushi). In the mocks the paragraph text reads "Supported types include: YouTube, Facebook, Vimeo, Twitch, and DailyMotion. View the complete list of support videos»"

Right, I had forgotten about this part, this is updated now @erikalogie

**Comment by erikalogie** [comment]
> > This looks great, but it would be also nice to have the hint in the paragraph with a link to this video plugin's documentation on github (I can't find the link but I know you sent that to me before @blushi). In the mocks the paragraph text reads "Supported types include: YouTube, Facebook, Vimeo, Twitch, and DailyMotion. View the complete list of support videos»"
> 
> Right, I had forgotten about this part, this is updated now @erikalogie

Great, looks good now!

**Pull request merged**
