### PR TITLE
feat: add loading spinner when file gets uploaded APP-10

### PR DESCRIPTION
**Pull request by blushi**
## Description

Closes: regen-network/rnd-dev-team#1880

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1. Go to https://deploy-preview-2326--regen-marketplace.netlify.app/ and log in
2. Create or edit project and go to the Media form
3. Try to upload a large image, you should see some loading spinner while it gets uploaded.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by clevinson** [comment]
Spinner looks good. Thanks @blushi!

One issue I ran into though, is that if you attempt to upload a 2nd gallery image while the first one is loading, then it overrides the first gallery image.  I think we should have a behavior where if you upload multiple images one at a time, each should be able to be in a loading state and you should see multiple images with the spinners representing the different images you've selected to upload.  Is that easy to configure the implementation to function this way?  If not, we can think about alternatives, like forcing users to wait until an upload finishes before adding a new photo.

**Comment by blushi** [comment]
> Spinner looks good. Thanks @blushi!
> 
> One issue I ran into though, is that if you attempt to upload a 2nd gallery image while the first one is loading, then it overrides the first gallery image. I think we should have a behavior where if you upload multiple images one at a time, each should be able to be in a loading state and you should see multiple images with the spinners representing the different images you've selected to upload. Is that easy to configure the implementation to function this way? If not, we can think about alternatives, like forcing users to wait until an upload finishes before adding a new photo.

You mean when selecting multiple files at once? We've got a dedicated issue to fix that: https://github.com/regen-network/rnd-dev-team/issues/1888

**Comment by blushi** [comment]
In response to @clevinson comments from 
https://github.com/regen-network/regen-web/pull/2328#issuecomment-2019146742 that belongs here I believe:

> Also, if you hit "Save & Next" while the spinner is still spinning, then the image does not save, and once the image upload finishes in the background I get a "Error: Request failed with status code 500" error a few seconds later when my browser is on the "Review" page.
> 
> To resolve this, I think we should probably have hte "Save & Next" button disabled while the spinners are loading. I don't know if I like the idea of greying them out whenever a "spinner" is spinning as that may look a bit erratic. @erikalogie do you have thoughts on this?

I think it makes sense in this case to disable the save button because it wouldn't make sense to save as is anyway because as long as it's still loading, that means we don't have yet the image URL uploaded to S3.

**Comment by erikalogie** [comment]
> 1. https://deploy-preview-2326--regen-marketplace.netlify.app/

Yes I agree with having the save and next button disabled while images are still uploading to s3.

**Comment by clevinson** [comment]
Some additional notes from my call with @blushi today:
- The "Drag & Drop / Add photo" prompt should not be visible while the spinner is loading
- Editing a photo results in an endless spinner (on main photo)

After a bit more discussion, @blushi and I think that it would be easier to implement if we instead had the loading spinner on the modal, since this prevents all other user behavior by default until the image is uploading.  Most of my bugs have to do with parallel uploading not being supported.

@erikalogie let's check in on this today?

**Comment by erikalogie** [comment]
> Some additional notes from my call with @blushi today:
> 
> * The "Drag & Drop / Add photo" prompt should not be visible while the spinner is loading
> * Editing a photo results in an endless spinner (on main photo)
> 
> After a bit more discussion, @blushi and I think that it would be easier to implement if we instead had the loading spinner on the modal, since this prevents all other user behavior by default until the image is uploading. Most of my bugs have to do with parallel uploading not being supported.
> 
> @erikalogie let's check in on this today?

Yes that makes sense, so having the loading spinner come up first on this cropper modal? https://www.figma.com/file/TyhFaXqko9F8OvLEE4Zomg/Issuer-Create%2FEdit-Projects%2C-Credit-Class%2C-Batches?type=design&node-id=2%3A4420&mode=design&t=2EiC2UfXONfzQCbP-1. Then once the image is uploaded, the cropper marks appear and the "apply" button is greyed out until then?

**Comment by blushi** [comment]
> > Some additional notes from my call with @blushi today:
> > 
> > * The "Drag & Drop / Add photo" prompt should not be visible while the spinner is loading
> > * Editing a photo results in an endless spinner (on main photo)
> > 
> > After a bit more discussion, @blushi and I think that it would be easier to implement if we instead had the loading spinner on the modal, since this prevents all other user behavior by default until the image is uploading. Most of my bugs have to do with parallel uploading not being supported.
> > @erikalogie let's check in on this today?
> 
> Yes that makes sense, so having the loading spinner come up first on this cropper modal? https://www.figma.com/file/TyhFaXqko9F8OvLEE4Zomg/Issuer-Create%2FEdit-Projects%2C-Credit-Class%2C-Batches?type=design&node-id=2%3A4420&mode=design&t=2EiC2UfXONfzQCbP-1. Then once the image is uploaded, the cropper marks appear and the "apply" button is greyed out until then?

yeah I think one option could be to just replace the "apply" button with a loading spinner while the image gets uploaded. Once the image is uploaded, the popup just closes.

**Comment by erikalogie** [comment]
> > > Some additional notes from my call with @blushi today:
> > > 
> > > * The "Drag & Drop / Add photo" prompt should not be visible while the spinner is loading
> > > * Editing a photo results in an endless spinner (on main photo)
> > > 
> > > After a bit more discussion, @blushi and I think that it would be easier to implement if we instead had the loading spinner on the modal, since this prevents all other user behavior by default until the image is uploading. Most of my bugs have to do with parallel uploading not being supported.
> > > @erikalogie let's check in on this today?
> > 
> > 
> > Yes that makes sense, so having the loading spinner come up first on this cropper modal? https://www.figma.com/file/TyhFaXqko9F8OvLEE4Zomg/Issuer-Create%2FEdit-Projects%2C-Credit-Class%2C-Batches?type=design&node-id=2%3A4420&mode=design&t=2EiC2UfXONfzQCbP-1. Then once the image is uploaded, the cropper marks appear and the "apply" button is greyed out until then?
> 
> This is not really what I imagined. I think one option could be to just replace the "apply" button with a loading spinner while the image gets uploaded, because **it's only once you hit the apply button that the image gets uploaded** (the cropped image, we don't upload the full image). Once the image is uploaded, the popup just closes.

Ok that would probably be fine. So the apply button would be greyed out and say something like "uploading image" with the spinner?

Another option is to have a loading bar across the top after you click the button, but that is less consistent with the circle spinner we have elsewhere.

**Comment by blushi** [comment]
> > > > Some additional notes from my call with @blushi today:
> > > > 
> > > > * The "Drag & Drop / Add photo" prompt should not be visible while the spinner is loading
> > > > * Editing a photo results in an endless spinner (on main photo)
> > > > 
> > > > After a bit more discussion, @blushi and I think that it would be easier to implement if we instead had the loading spinner on the modal, since this prevents all other user behavior by default until the image is uploading. Most of my bugs have to do with parallel uploading not being supported.
> > > > @erikalogie let's check in on this today?
> > > 
> > > 
> > > Yes that makes sense, so having the loading spinner come up first on this cropper modal? https://www.figma.com/file/TyhFaXqko9F8OvLEE4Zomg/Issuer-Create%2FEdit-Projects%2C-Credit-Class%2C-Batches?type=design&node-id=2%3A4420&mode=design&t=2EiC2UfXONfzQCbP-1. Then once the image is uploaded, the cropper marks appear and the "apply" button is greyed out until then?
> > 
> > 
> > This is not really what I imagined. I think one option could be to just replace the "apply" button with a loading spinner while the image gets uploaded, because **it's only once you hit the apply button that the image gets uploaded** (the cropped image, we don't upload the full image). Once the image is uploaded, the popup just closes.
> 
> Ok that would probably be fine. So the apply button would be greyed out and say something like "uploading image" with the spinner?

Yes that could work.

> 
> Another option is to have a loading bar across the top after you click the button, but that is less consistent with the circle spinner we have elsewhere.

Indeed, and would need more work to actually reflect the upload progress.

**Comment by blushi** [comment]
> > > This is not really what I imagined. I think one option could be to just replace the "apply" button with a loading spinner while the image gets uploaded, because **it's only once you hit the apply button that the image gets uploaded** (the cropped image, we don't upload the full image). Once the image is uploaded, the popup just closes.
> > 
> > 
> > Ok that would probably be fine. So the apply button would be greyed out and say something like "uploading image" with the spinner?
> 
> Yes that could work.

@clevinson @erikalogie any thoughts?

**Comment by erikalogie** [comment]
> > > > This is not really what I imagined. I think one option could be to just replace the "apply" button with a loading spinner while the image gets uploaded, because **it's only once you hit the apply button that the image gets uploaded** (the cropped image, we don't upload the full image). Once the image is uploaded, the popup just closes.
> > > 
> > > 
> > > Ok that would probably be fine. So the apply button would be greyed out and say something like "uploading image" with the spinner?
> > 
> > 
> > Yes that could work.
> 
> @clevinson @erikalogie any thoughts?

I think try it with the spinner in the button

**Comment by clevinson** [comment]
Yep this approach seems correct to me!

**Comment by blushi** [comment]
@erikalogie @clevinson I've updated it to have the spinner in the button

**Comment by erikalogie** [comment]
@blushi this looks good.

**Review by clevinson — APPROVED** [review]

**Comment by blushi** [comment]
> @blushi this flow looks great. Thanks!
> 
> One issue that I ran into when testing out this flow is that when selecting multiple images at once in the file browser, only the last upload gets set as a gallery image.
> 
> Here's the steps I followed:
> 
> * in gallery images edit form, click "Add photo" button
> * Select multiple photos from the browser
> * Go through cropping & caption flow for each photo (waiting for the spinner to finish on each one)
> * At the end, only the last photo is displayed as having been successfully uploaded into the gallery
> 
> I think this is tracked already in [APP-18](https://regennetwork.atlassian.net/jira/software/c/projects/ENG/boards/51?selectedIssue=APP-18) though? So maybe we can merge this, and just tackle APP-18 in a follow up?

Yes indeed

**Review by aaronc — APPROVED** [review]

**Pull request merged**
