### PR TITLE
fix: APP-147 project size always displayed as hectares in BasicInfoForm

### PR DESCRIPTION
**Pull request by blushi**
## Description

https://regennetwork.atlassian.net/browse/APP-147?atlOrigin=eyJpIjoiNmM4NzUwMzQzODVhNDM5MWI4NjAwNDY5MWU4N2I3Y2EiLCJwIjoiaiJ9

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

From https://deploy-preview-2386--regen-marketplace.netlify.app/, create or edit a new project.
Update the project size to use "acres" and save.
Going back to the basic info form, it should show the right size unit.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@clevinson see testing instructions

**Comment by blushi** [comment]
@erikalogie see testing instructions

**Review by aaronc — APPROVED** [review]

**Review by clevinson — APPROVED** [review]
tACK

**Comment by erikalogie** [comment]
Ok, this seems to be working on the create form but now I am having the issues that no ISO codes will save and I can't change the location in the create form so I can't confirm this after publish. I just checked and this is an issue happening on dev, not just this branch.
https://github.com/regen-network/regen-web/assets/8460237/e95c43ed-7d33-4882-a8e5-47b79f91f644

Also in the edit form this does not seem to be working at all:
https://github.com/regen-network/regen-web/assets/8460237/c0f9f0a9-072d-4834-9f3a-a5c8f8ec7079

Another thing I'm noticing that is probably unrelated, should I open a ticket for this? When you click the back button, the user shouldn't get the intro popup again:
https://github.com/regen-network/regen-web/assets/8460237/1c7ef657-9595-405a-848e-b96e2eb16b87

**Comment by erikalogie** [comment]
> > Ok, this seems to be working on the create form but now I am having the issues that no ISO codes will save and I can't change the location in the create form so I can't confirm this after publish. I just checked and this is an issue happening on dev, not just this branch.
> > https://github.com/regen-network/regen-web/assets/8460237/e95c43ed-7d33-4882-a8e5-47b79f91f644
> 
> Could you create a separate bug for that? It looks like we might not always be able to retrieve the ISO code from the provided location.

Ok done, here: https://regennetwork.atlassian.net/browse/APP-192
> 
> > Also in the edit form this does not seem to be working at all:
> > https://github.com/regen-network/regen-web/assets/8460237/c0f9f0a9-072d-4834-9f3a-a5c8f8ec7079
> 
> I believe this is more an issue with this project in particular because project size change should trigger transaction signing but it's not, which is why it's not saved. After some debugging, it seems this project C01-005 was in a weird state, it should work ok now.

You are right, this is working correctly with another project.
> 
> > Another thing I'm noticing that is probably unrelated, should I open a ticket for this? When you click the back button, the user shouldn't get the intro popup again:
> > https://github.com/regen-network/regen-web/assets/8460237/1c7ef657-9595-405a-848e-b96e2eb16b87
> 
> yes let's create a separate issue for that too.

Ok, done: https://regennetwork.atlassian.net/browse/APP-193

**Pull request merged**
