### PR TITLE
feat: use dark topographic section

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/regen-registry#1472

- use dark topographic background when dark mode is activated

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1.  https://deploy-preview-1917--regen-registry.netlify.app/

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie I made this PR as a quick for the current dark mode version because I think it will take us some time to figure out dark mode entirely. It changes only the dark topo background for the home and the text on top of it, let me know what you think: https://deploy-preview-1917--regen-registry.netlify.app/

**Comment by erikalogie** [comment]
> @erikalogie I made this PR as a quick for the current dark mode version because I think it will take us some time to figure out dark mode entirely. It changes only the dark topo background for the home and the text on top of it, let me know what you think: https://deploy-preview-1917--regen-registry.netlify.app/

This looks pretty good but it shows up in the light mode as well as dark mode. Was that your intention?

Also, I think that we should use the svg version of the dark topography background with green lines on top and have it displayed at its original size with a repeating background, more similar to how it appear in the comps (in both dark and light mode) i.e.: https://www.figma.com/file/Md1Cl2B9eJi4NMzQgpbdMF/Dark-Mode?type=design&node-id=1%3A688&t=qIdNl85jNjVhZgWe-1 and https://www.figma.com/file/seUiQM2SPt78KJiDL0Ea8m/Basic-Ecocredits-Ledger-View-%2F-Marketplace?type=design&node-id=6444%3A186757&t=kmI1QkSwqiNLFdkx-1. Right now it looks pretty big and stretched out. I realize that is how it currently looks on live but that can be fixed pretty easily with "background-size: auto;
    background-repeat: repeat;" as long as the svgs are sized to the same size, which they should be but let me know if you need my assistance with that.

**Comment by erikalogie** [comment]
> https://deploy-preview-1917--regen-registry.netlify.app/

Ok, the sizing of the topography on light mode looks good, though the dark mode does not match (it is still stretched out... unless that fix is not yet deployed?).

I don't think that we really want to just have this one section look dark if the system preference is for dark. I would suggest we don't merge this work until the rest of the dark mode work has been implemented because it looks pretty funky to just have this one section dark.

**Comment by flagrede** [comment]
@erikalogie should be deployed now, it's using `auto` and `repeat` on the background now.
Just wanted to note that after exploring the app a bit this morning with the new palette we're really far from having a dark mode that we can put in production than I thought, probably several sprints away (given that we can allocate a decent amount of time on each next sprint). That's why I wanted to push this in the meantime for Keplr mobile users since they represent a significant part of the traffic.
I could activate the dark section only on mobile maybe?

**Comment by flagrede** [comment]
@erikalogie I was able to trigger the dark mode only for Keplr mobile web. I forced the flag temporarily on the deploy preview so you can check what it looks like, all sections using a topo background should now use the dark one instead. In order to test you should use a chrome browser with the force dark flag on to emulate Kepkr behavior.

**Comment by erikalogie** [comment]
> @erikalogie I was able to trigger the dark mode only for Keplr mobile web. I forced the flag temporarily on the deploy preview so you can check what it looks like, all sections using a topo background should now use the dark one instead. In order to test you should use a chrome browser with the force dark flag on to emulate Kepkr behavior.

Amazing!! This looks good. Btw the other place where this is really bad is the top of the Credit Class pages. Would it be possible to fix that too quickly?

**Comment by flagrede** [comment]
@erikalogie I missed this one, should be fixed.

**Comment by erikalogie** [comment]
> @erikalogie I missed this one, should be fixed.

great! looks good

**Pull request merged**
