### PR TITLE
feat: update project review

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/regen-registry#1673
Closes: regen-network/regen-registry#1704

Update review step with:
- gallery photos
- caption and credit for photos
- story media (image/video)

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1. https://deploy-preview-1905--regen-registry.netlify.app/project-pages/0551d790-b68c-11ed-9317-0267c2be097b/review (on the shared account)

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie you can check what the updated media section preview look like here: https://deploy-preview-1905--regen-registry.netlify.app/project-pages/0551d790-b68c-11ed-9317-0267c2be097b/review (this is a project link from the shared account).

**Comment by erikalogie** [comment]
@flagrede yes some funky stuff is going on for me too, the images are blank: https://monosnap.com/file/K4vPBNn99PbsC4wqBGtmTMFOd9j9oG

And if I go to try and edit them, I can't hit the "save and next" button because it is greyed out.

**Comment by flagrede** [comment]
@erikalogie @wgwz The preview link is fixed. Not sure what happened here, but the db end up with images with empty URL which explain why you could no longer submit Erika.
I'm investigating this issue in a separate ticket but I can't reproduce it so far, could share some details on how it happened @wgwz (like did you swap you account just before testing) ?

**Comment by flagrede** [comment]
@wgwz Nevermind I found the issue, there was a problem with the submit, will make a fix.

**Comment by flagrede** [comment]
@erikalogie are we good on how the review step looks with the new media images/video?

**Comment by erikalogie** [comment]
> @erikalogie are we good on how the review step looks with the new media images/video?

Yes, looks good!

**Comment by wgwz** [comment]
tACK - created a project successfully, and the corresponding project page looks good!

**Review by wgwz — APPROVED** [review]

**Pull request merged**
