### PR TITLE
feat:  ecosystem activity tags project page

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/regen-registry#1590
Sanity PR: https://github.com/regen-network/regen-sanity/pull/41

Add:
- ProjectTag molecule
- ProjectTags Organisms
- Sanity requests to get projects activity and ecosystem icons
- Display project ecosystem an activity with icons on project page

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

Project page: https://deploy-preview-1936--regen-registry.netlify.app/project/C02-024
Storybook: https://deploy-preview-1936--regen-storybook.netlify.app/?path=/story/organisms-projecttags--default

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie you can check the ecosystem and activity tags here: https://deploy-preview-1936--regen-registry.netlify.app/project/C02-024
Fore a more complex UI test example you can check storybook: https://deploy-preview-1936--regen-storybook.netlify.app/?path=/story/organisms-projecttags--default

**Comment by flagrede** [comment]
@erikalogie I was able to handle that, you can check it here: https://deploy-preview-1936--regen-storybook.netlify.app/?path=/story/organisms-projecttags--default
I created 2 additional stories with the 1/3 and 1/1 content version.

**Comment by erikalogie** [comment]
@flagrede looks great!

**Review by wgwz — APPROVED** [review]
utACK

**Pull request merged**
