### PR TITLE
feat: add OTC sales option

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/regen-registry#1560
Sanity PR: https://github.com/regen-network/regen-sanity/pull/27

Show OTC sale option modal when trying to buy for an unconnected user.

Add components:
- ActionCard (molecules)
- InfoCard (molecules)
- BuyModalOptions (organisms)

Update:
- BuyCreditsModal (use InfoCard)

Wire sanity content:
- buyModalOptions (used in `BuySellOrderFlow` > `BuyModalOptions`)
- buyModal (used in `BuyCreditsModal`)
---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed
- [ ] once the PR is closed, set up backport PRs for `redwood`, `hambach` and optionally `master` (see below)

#### Setting up backport PRs

After merging your PR to `dev`, set up backports by doing the following:

1. If your branch does not have merge commits, add the following comment to
   your PR:

- If PR is a new feature: `@Mergifyio backport redwood hambach`.
- If PR is a bug fix: `@Mergifyio backport redwood hambach master`.

2. If your branch does have merge commits:

   a. Pull latest `dev`, `hambach` and `redwood` branches

   b. Create new branches for backports and merge `dev` (replace `<PR#>` with your PR #)

   ```
   git checkout -b hambach-backport-<PR#> hambach
   git merge dev
   git push origin hambach-backport-<PR#>
   git checkout -b redwood-backport-<PR#> redwood
   git merge dev
   git push origin redwood-backport-<PR#>`
   ```

   c. Open new PRs in regen-web targeting `hambach` and `redwood`, respectively.

   d. If PR is a bug fix repeat the same process for `master` branch.

### How to test

1. https://deploy-preview-1801--regen-registry.netlify.app/

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by erikalogie** [comment]
> @erikalogie here's the link to check the new OTC sale options: https://deploy-preview-1801--regen-registry.netlify.app/ The buy credits button is currently wired to the `/storefront` page (from sanity). Let me know if you want to display the error banner instead when clicking it.

Great work! Yes, the error banner should be displayed instead of the /storefront page. I hope we can make this keplr warning popup to replace that red banner soon.

Also, this OTC popup should appear when clicking "buy" on the project pages and credit class pages. The main header should say "Choose how to purchase credits" rather than "select a wallet".

On mobile, it is a bit hard to read the bottom header. I modified the image a bit (attached) so that the USDC and Regen coin icons are lighter so the black text is more legible. If it is still hard to read, then maybe we should also add some more padding at the bottom of the boxes on mobile, something like this: https://monosnap.com/file/MUWh4EgncTBIGTOsN2EhXU60bEm6CN


Keplr Wallet

**Comment by flagrede** [comment]
@erikalogie I handled all your feedback. Let me know what you think of the readability on mobile with the new logo.

**Comment by erikalogie** [comment]
> @erikalogie I handled all your feedback. Let me know what you think of the readability on mobile with the new logo.

Great, this looks good! I think the readability could still be better, but I can change the graphic later in the CMS rather than have you tweak it more.

**Comment by blushi** [comment]
If I click on "schedule a call", I just get the error banner "Please connect to Keplr...":
image

**Comment by flagrede** [comment]
> If I click on "schedule a call", I just get the error banner "Please connect to Keplr...": image

@blushi I made a regression while handling Erika's feedback, will fix it.

**Review by blushi — APPROVED** [review]
tACK

**Pull request merged**
