### PR TITLE
feat: add sentry setup including support for react router

### PR DESCRIPTION
**Pull request by wgwz**
## Description

Closes: https://github.com/regen-network/regen-registry/issues/1110

Adds integration to Sentry, following the guide for Sentry <> React:

https://docs.sentry.io/platforms/javascript/guides/react/

Thus far, capturing un-tracked exceptions and integration with `react-router-dom` is configured. We may want to consider adding support for ["react error boundaries"](https://docs.sentry.io/platforms/javascript/guides/react/components/errorboundary/) but I don't know what those are and if they make sense for our application. Feedback on that will be appreciated. 

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed
- [ ] once the PR is closed, set up backport PRs for `redwood` and `hambach` (see below)

#### Setting up backport PRs

After merging your PR to `master`, set up backports by doing the following:

1. If your branch does not have merge commits, add the following comment to
   your PR, `@Mergifyio backport redwood hambach`.

2. If your branch does have merge commits:

    a. Pull latest `master`, `hambach` and `redwood` branches

    b. Create new branches for backports and merge `master` (replace `<PR#>` with your PR #)
    ```
    git checkout -b hambach-backport-<PR#> hambach
    git merge master
    git push origin hambach-backport-<PR#>
    git checkout -b redwood-backport-<PR#> redwood
    git merge master
    git push origin redwood-backport-<PR#>`
    ```

    c. Open new PRs in regen-web targeting `hambach` and `redwood`, respectively.
  

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by wgwz** [comment]
Here is an example of an issue caught from this PRs deploy preview (generated by clicking the NCT tab):

https://sentry.io/share/issue/350f9a8574574ed48426c4a6dea685f7/

**Review by haveanicedavid — APPROVED** [review]
lgtm - nice work!

**Comment by victordelval** [comment]
@wgwz error boundaries are a mechanism in react to create a wrapper component over another component (tree) with (a lot of?) logic, likely to fail. To catch unhandled errors and avoid blank screen (by passing some fallback component).

I think we are not using, but it is interesting

**Comment by haveanicedavid** [comment]
Error boundaries are definitely nice to have for uncaught exceptions, and easy to set up. Could write our own, but my default is just to use [react error boundary](https://github.com/bvaughn/react-error-boundary). 

You can see an example in my groups work [here](https://github.com/haveanicedavid/groups-ui/blob/main/src/App.tsx) (error boundary component [here](https://github.com/haveanicedavid/groups-ui/blob/main/src/App.tsx))

**Comment by haveanicedavid** [comment]
FWIW, I also prefer having custom error handling at the top level which can take the error return from a `catch` block, guarantee it has a `message` property, and do something with the error message: https://github.com/haveanicedavid/groups-ui/blob/main/src/util/errors.ts

**Review by flagrede — APPROVED** [review]
Nice one, looks good !

**Comment by wgwz** [comment]
I'm going to open a separate task for considering error boundaries and integrating that with our Sentry setup, since it will require some more changes to our code. 

https://github.com/regen-network/regen-registry/issues/1183

**Comment by wgwz** [comment]
@Mergifyio backport redwood hambach

**Comment by wgwz** [comment]
@Mergifyio backport hambach

**Comment by wgwz** [comment]
@Mergifyio backport hambach

**Pull request merged**
