### PR TITLE
feat: APP-396 two decimal digits for usd amount

### PR DESCRIPTION
**Pull request by r41ph**
## Description

https://regennetwork.atlassian.net/browse/APP-396

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1. https://deploy-preview-2544--regen-marketplace.netlify.app/project/mai-ndombe-4/buy
2. Verify that the currency input when set to USD only accepts two decimals.
3. Verify that an error is shown when the amount of USD is less than 0.50

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by r41ph** [comment]
@erikalogie one thing to consider is if we want to round up the currency amount when in USD because when we cut the decimals o two we may end up charging less than the actual credits price - let me know what you think

**Comment by blushi** [comment]
> @erikalogie one thing to consider is if we want to round up the currency amount when in USD because when we cut the decimals o two we may end up charging less than the actual credits price - let me know what you think

@erikalogie @S4mmyb any thoughts on this?
Imagine the exact amount is $10.897, should we charge 10.89 or 10.90?

**Comment by erikalogie** [comment]
> > @erikalogie one thing to consider is if we want to round up the currency amount when in USD because when we cut the decimals o two we may end up charging less than the actual credits price - let me know what you think
> 
> @erikalogie @S4mmyb any thoughts on this? Imagine the exact amount is $10.897, should we charge 10.89 or 10.90?

I think we should round up to $10.90 in this case

**Comment by blushi** [comment]
> > > @erikalogie one thing to consider is if we want to round up the currency amount when in USD because when we cut the decimals o two we may end up charging less than the actual credits price - let me know what you think
> > 
> > 
> > @erikalogie @S4mmyb any thoughts on this? Imagine the exact amount is $10.897, should we charge 10.89 or 10.90?
> 
> I think we should round.

> I think we should round up to $10.90 in this case

Ok so if it were $10.894, we would charge 10.89.

**Comment by S4mmyb** [comment]
> > > > @erikalogie one thing to consider is if we want to round up the currency amount when in USD because when we cut the decimals o two we may end up charging less than the actual credits price - let me know what you think
> > > 
> > > 
> > > @erikalogie @S4mmyb any thoughts on this? Imagine the exact amount is $10.897, should we charge 10.89 or 10.90?
> > 
> > 
> > I think we should round.
> 
> > I think we should round up to $10.90 in this case
> 
> Ok so if it were $10.894, we would charge 10.89.

Yep! <5 we round down, >=5 round up for that third decimal place.

**Comment by r41ph** [comment]
@blushi @erikalogie @S4mmyb have a look at this please

**Comment by erikalogie** [comment]
I think the translation string is missing for the error:
Screenshot 2024-12-03 at 11 41 28 AM

**Review by blushi — COMMENTED** [review]
Looks good overall. One thing: If I type leading zeros in the currency input, then it's only transformed into a correct value, eg 0.1 when I type the final 1, while for the credits amount input, as long as I have one leading zero, I can't get others
I think both inputs should have consistent behaviors

image

**Review by blushi — APPROVED** [review]
Pre-approving
Pending @erikalogie to have another look and translation to be fixed:

image
this shows up when I enter an amount lower than < 50 cents

**Comment by erikalogie** [comment]
> Pre-approving Pending @erikalogie to have another look and translation to be fixed:
> 
> image this shows up when I enter an amount lower than < 50 cents

Let me know when this is fixed and I'll test again @r41ph

**Comment by r41ph** [comment]
@erikalogie please have look, the translation should be fixed now

**Comment by blushi** [comment]
> @erikalogie please have look, the translation should be fixed now

@r41ph could you run i18n:extract so it translates the missing es translations for "Must be at least"?

**Pull request merged**
