### PR TITLE
feat: APP-324 Tebu Banner

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Add the Tebu Banner component and use it on the projects page.

Sanity PR: https://github.com/regen-network/regen-sanity/pull/67

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie You can have a look at the Tebu Banner here: https://deploy-preview-2485--regen-marketplace.netlify.app/projects/1
Should we save the closed state in local storage so we can hide the banner on further visits, or should we reopen it every time?

**Comment by erikalogie** [comment]
> @erikalogie You can have a look at the Tebu Banner here: https://deploy-preview-2485--regen-marketplace.netlify.app/projects/1 Should we save the closed state in local storage so we can hide the banner on further visits, or should we reopen it every time?

Let's save the closed state in local storage.

This looks great! Just two small design things: the card background should be white and the paragraph text should be 14px on mobile.

**Comment by erikalogie** [comment]
Also let's reduce the space above and below the component on mobile: 
Monosnap Regen Marketplace 2024-09-26 11-37-38

See this comp for more clarity on that: https://www.figma.com/design/brkxGV5qNOkZUp0YQl1cxO/Terrasos-Phase-1?node-id=708-86974&t=BLbnCULySCl3T9L2-1

**Comment by flagrede** [comment]
@erikalogie I have handled your feedback.

**Review by wgardiner — APPROVED** [review]
Looks good!

**Pull request merged**
