### PR TITLE
feat: APP-24 create post

### PR DESCRIPTION
**Pull request by blushi**
## Description

https://regennetwork.atlassian.net/browse/APP-24?atlOrigin=eyJpIjoiZTY0MWE1MDRiOTlhNDJjMzlkNTE1ODUzNDUyMDBhYjUiLCJwIjoiaiJ9
closes: #2266
(will also fix https://regennetwork.atlassian.net/browse/APP-190?atlOrigin=eyJpIjoiM2Q5ZDlhOTE0Yjc0NDUwNThmMmI0NTA1NzFjNDMyODgiLCJwIjoiaiJ9)

needs: https://github.com/regen-network/regen-server/pull/469

This doesn't include the "Attest" signing part of the flow since it's pending https://github.com/regen-network/regen-server/pull/454. Follow-up task to address that: https://regennetwork.atlassian.net/browse/APP-183?atlOrigin=eyJpIjoiZmM0ZWU5Njk5ODcwNGY3NWFkMmUwNjNmNGM0ZDgxZjQiLCJwIjoiaiJ9

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1. Log in from https://deploy-preview-2381--regen-marketplace.netlify.app/
2. Go to your projects. Try to to create a post using the new dedicated button on your projects cards.
3. Add different types of files with different types of location and different privacy settings. NB: when selecting a file, it's uploaded directly so there might be some time before you see the file name in the "edit a file" popup. @erikalogie and I were discussing some ways to improve that but we haven't come to a conclusion yet, we'll need to implement some UX tweaks to that when she's back.
4. "Create post" button should be disabled for draft projects or projects without location

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by aaronc — APPROVED** [review]
utACK

**Comment by blushi** [comment]
@erikalogie see testing instructions

**Comment by erikalogie** [comment]
@blushi one thing I'm noticing is that if I select multiple files, only the first one gets the "Edit your file" popup. So although I can select multiple files, it doesn't really work.

What do you think about a popup like this while each file is uploading? https://www.figma.com/design/Bksz1JeDYxQVIXdI46EgPT/Project-Posts?node-id=3855-54800&t=Gzfbf9TVdnkX01iP-1

**Comment by blushi** [comment]
> @blushi one thing I'm noticing is that if I select multiple files, only the first one gets the "Edit your file" popup. So although I can select multiple files, it doesn't really work.

Fixed.

> What do you think about a popup like this while each file is uploading? https://www.figma.com/design/Bksz1JeDYxQVIXdI46EgPT/Project-Posts?node-id=3855-54800&t=Gzfbf9TVdnkX01iP-1

Added.

**Comment by erikalogie** [comment]
I'm getting this error "Error: Cannot upload file without a project id" when I try to select a file to file to upload from any of the completed projects on the primary testing account.

https://github.com/regen-network/regen-web/assets/8460237/4c43c90f-b4f3-490a-84d9-3ef88295c3fc

**Comment by blushi** [comment]
> I'm getting this error "Error: Cannot upload file without a project id" when I try to select a file to file to upload from any of the completed projects on the primary testing account.
> 
>  Screen.Recording.2024-06-20.at.9.09.14.AM.mov

@erikalogie this should be fixed!

**Comment by erikalogie** [comment]
It looks like if I select multiple files, then the second file and third file, etc that have been uploaded, do not have "no specific location" selected by default.

**Comment by blushi** [comment]
> It looks like if I select multiple files, then the second file and third file, etc that have been uploaded, do not have "no specific location" selected by default.

This should work properly now.

**Comment by blushi** [comment]
> Ok, now I just tried it with a few files and the second one does not load the map but first and third do. Also, you may notice at the end of the video the delete icon looks weird?
> 
>  Screen.Recording.2024-06-24.at.5.11.17.PM.mov



> Ok, now I just tried it with a few files and the second one does not load the map but first and third do. Also, you may notice at the end of the video the delete icon looks weird?
> 
>  Screen.Recording.2024-06-24.at.5.11.17.PM.mov

@erikalogie could you try again? I also fixed the delete icon.

**Comment by erikalogie** [comment]
The delete icon looks good but the same thing is happening with the map not showing up on the second image.

**Pull request merged**
