### PR TITLE
fix: privacy and terms pages

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/rnd-dev-team#1788

- Fix privacy and terms page

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1. https://deploy-preview-2096--regen-website.netlify.app/terms-service
2. https://deploy-preview-2096--regen-website.netlify.app/privacy-policy

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie you can check that the two pages, terms and privacy, have been added back.
https://deploy-preview-2096--regen-website.netlify.app/terms-service
https://deploy-preview-2096--regen-website.netlify.app/privacy-policy

**Comment by erikalogie** [comment]
@flagrede this looks good, though it does seem that our terms of service for the website are old, as it still refers to the Marketplace as the Registry and uses our old corporate name, "Regen Network Development, Inc" rather than "Regen Network Development, PBC". I wonder if we should at least do a find and replace for the corporate name to change that and I can ask about getting these terms updated otherwise.

**Comment by flagrede** [comment]
@erikalogie I think a proper update would be needed, I might mess up some parts by doing the search and replace with Marketplace/Registry.

**Comment by erikalogie** [comment]
Ok, I was suggesting just changing the corporate name, but this can also be done separately if that makes you nervous.

**Comment by blushi** [comment]
> @erikalogie I think a proper update would be needed then, I might mess up some parts by doing the search and replace with Marketplace/Registry.

In this case, you would just need to search for "Regen Network Development, Inc" and replace.

**Comment by flagrede** [comment]
@blushi @erikalogie if it's just "Regen Network Development, Inc" then it's not a problem, will update the PR.

**Review by blushi — APPROVED** [review]
looks good

**Pull request merged**
