### PR TITLE
fix: hide empty additional info on project and credit class pages

### PR DESCRIPTION
**Pull request by blushi**
## Description

Closes: regen-network/rnd-dev-team#1822

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

- On chain project with metadata: https://deploy-preview-2231--regen-marketplace.netlify.app/project/C01-001 additional info tab with project id and metadata
- On chain project without metadata: https://deploy-preview-2231--regen-marketplace.netlify.app/project/C01-002 additional info tab with project id only
- Off chain project: https://deploy-preview-2231--regen-marketplace.netlify.app/project/wilmot no additional info tab
- On chain credit class with metadata: https://deploy-preview-2231--regen-marketplace.netlify.app/credit-classes/C01 additional info tab with class id and metadata
- On chain credit class without metadata: https://deploy-preview-2231--regen-marketplace.netlify.app/credit-classes/C50 additional info tab with class id only

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by aaronc** [comment]
How should this be tested @blushi ?

**Comment by blushi** [comment]
> How should this be tested @blushi ?

Just added the testing instructions to the PR description

**Comment by blushi** [comment]
> > How should this be tested @blushi ?
> 
> Just added the testing instructions to the PR description

cc/ @erikalogie

**Review by flagrede — APPROVED** [review]
Looks good!

**Comment by erikalogie** [comment]
LGTM!

**Pull request merged**
