### PR TITLE
fix: CI build failing on node v18

### PR DESCRIPTION
**Pull request by blushi**
## Description

CI on regen-web is now running on node v18, which causes our build job to fail for various reasons:
- on `yarn install` we have apollo CLI as part of our dev dep, which is being deprecated (in particular @apollo/federation which causes the following issue: https://github.com/regen-network/regen-web/actions/runs/4230442490/jobs/7347771965) I don’t think we really use it, so we can rm it
- then we still have an issue on `yarn build` : https://github.com/regen-network/regen-web/actions/runs/4225237751/jobs/7337252031 solution: https://github.com/webpack/webpack/issues/14532
- finally we still had an issue with `yarn test` related to Buffer not being defined: https://github.com/regen-network/regen-web/actions/runs/4230757522/jobs/7348460931, tried to use `react-app-wired test` (instead of `react-scripts test`) and add buffer to webpack config fallback/plugins but we're still using webpack 4 (as resolution) and fallbacks are not supported so we would need to do some larger work on upgrading this. Since we'll move away from CRA anyway (https://github.com/regen-network/regen-registry/issues/1316 or https://github.com/regen-network/regen-registry/issues/1170), @flagrede and I discussed that it might not be worth it to spend too much time on that, so instead we're just disabling the tests on CI temporarily. We don't have major tests so this should be fine.

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed
- [ ] once the PR is closed, set up backport PRs for `redwood`, `hambach` and optionally `master` (see below)

#### Setting up backport PRs

After merging your PR to `dev`, set up backports by doing the following:

1. If your branch does not have merge commits, add the following comment to
   your PR:

- If PR is a new feature: `@Mergifyio backport redwood hambach`.
- If PR is a bug fix: `@Mergifyio backport redwood hambach master`.

2. If your branch does have merge commits:

   a. Pull latest `dev`, `hambach` and `redwood` branches

   b. Create new branches for backports and merge `dev` (replace `<PR#>` with your PR #)

   ```
   git checkout -b hambach-backport-<PR#> hambach
   git merge dev
   git push origin hambach-backport-<PR#>
   git checkout -b redwood-backport-<PR#> redwood
   git merge dev
   git push origin redwood-backport-<PR#>`
   ```

   c. Open new PRs in regen-web targeting `hambach` and `redwood`, respectively.

   d. If PR is a bug fix repeat the same process for `master` branch.

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@blushi I just noticed that only one test failed (`App.tsx`) because of the `Buffer` issue. Should we disable this one only instead?

**Comment by blushi** [comment]
@flagrede good point, updated

**Comment by flagrede** [comment]
@blushi seems like the test is still pick-up by jest, maybe we can try to rename the file to `App.test.disabled.tsx`?

**Comment by blushi** [comment]
hum seems like App.test.tsx is ignored now but tests are still failing, and the buffer error comes from a .stories.tsx file

**Comment by flagrede** [comment]
> hum seems like App.test.tsx is ignored now but tests are still failing, and the buffer error comes from a .stories.tsx file

@blushi weird... let's go back to the initial plan then I guess.

**Pull request merged**
