### PR TITLE
feat: APP-108 edit/view project buttons

### PR DESCRIPTION
**Pull request by blushi**
## Description

https://regennetwork.atlassian.net/browse/APP-108?atlOrigin=eyJpIjoiNDUwN2E3NGNkNDhkNDNkMmIxNGVmMzE5YTFhNTNlMDAiLCJwIjoiaiJ9

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1. Log in from https://deploy-preview-2351--regen-marketplace.netlify.app/
2. Edit one of your published project, you should need the new "view project" button that opens up the project page in a new tab
3. On a project page you're an admin of, the bottom banner should just have one button to "edit project", try to edit both an offchain and an onchain project from there

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie see testing instructions

**Comment by erikalogie** [comment]
LGTM! On second thought @blushi I think we should have the "view project" open in the same window/tab.

**Review by aaronc — APPROVED** [review]
utACK

**Comment by blushi** [comment]
> LGTM! On second thought @blushi I think we should have the "view project" open in the same window/tab.

@erikalogie updated

**Comment by erikalogie** [comment]
> > LGTM! On second thought @blushi I think we should have the "view project" open in the same window/tab.
> 
> @erikalogie updated

LGTM!

**Pull request merged**
