### PR TITLE
chore: update company title from inc to pbc

### PR DESCRIPTION
**Pull request by ryanchristo**
## Description

Part of: regen-network/regen-registry#1456

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1. Confirm updated company title in footer of website and application
- https://deploy-preview-2002--regen-website.netlify.app/
- https://deploy-preview-2002--regen-registry.netlify.app/

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by blushi — APPROVED** [review]
LGTM
As part of this task, I think we should also go through the sanity content to update any mention to "Inc", if you have time @ryanchristo or @erikalogie could also have a look.
Here's one example we have in the Blog section of the website homepage: 
image

**Review by blushi — CHANGES_REQUESTED** [review]
Actually we also need to change the link for the "How-to articles" to: https://guides.regen.network/guides/regen-marketplace

**Comment by erikalogie** [comment]
@blushi I just noticed that on the website all the links under "registry" are broken except for the methodology library link. Should that be fixed as part of this issue or a separate one?

**Comment by erikalogie** [comment]
And actually I think we don't want the registry link under Community to link to the notion site anymore but to the handbook

**Comment by blushi** [comment]
Yeah I believe this should be fixed asap.
Let's also make sure that the registry team communicates with us when they update pages on https://registry.regen.network/...

**Comment by blushi** [comment]
> Yeah I believe this should be fixed asap. Could you update the description accordingly? Let's also make sure that the registry team communicates with us when they update pages on https://registry.regen.network/...

**Comment by blushi** [comment]
Could you update the description accordingly @erikalogie? thanks

**Comment by erikalogie** [comment]
Updated @blushi

**Comment by ryanchristo** [comment]
Are the other updates all set now? Are there any changes that need to be made within this repository?

**Review by wgwz — APPROVED** [review]
LGTM!

**Review by blushi — COMMENTED** [review]
We're still missing the other changes mentioned in the issue:

> Change link for the "How to articles" to: https://guides.regen.network/guides/regen-marketplace
> 
> Fixes to links on website footer:
> - Registry: https://registry.regen.network/
> - Program guide (app and website footer): https://registry.regen.network/v/regen-registry-handbook/regen-registry-overview/program-rules-and-requirements
> - Create a methodology: https://registry.regen.network/v/regen-registry-handbook/methodology-development/methodology-development-overview
> - Methodology review: https://registry.regen.network/v/regen-registry-handbook/methodology-development/methodology-review-process

**Comment by ryanchristo** [comment]
I believe Tica is updating the registry gitbook so I guess we will need to wait for her to finished before merging this then.

**Comment by ryanchristo** [comment]
I did find another reference in the regen ledger docs which is now merged and deployed.

**Review by blushi — APPROVED** [review]
approving, as agreed let's tackle the remaining changes separately https://github.com/regen-network/regen-web/pull/2010#issuecomment-1669023998

**Pull request merged**
