### PR TITLE
feat: add warning modal on profile edit

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/rnd-dev-team#1592

- display warning modal, with draft changes, on profile edit

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1. https://deploy-preview-2144--regen-marketplace.netlify.app/profile/edit

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@flagrede have you discussed with @erikalogie if the current behavior is ok? meaning we don't show the modal on **any** route changes but only on the one(s) that can happen from the edit profile form itself.

**Comment by flagrede** [comment]
@blushi Not yet, planned to tag her here.

@erikalogie Hey Erika, I've added the warning modal whenever clicking `VIEW PROFILE`. 
Regarding the other nav links (in the header), I would not recommend applying the same behavior here because that would mean we would have to listen to navigation changes everywhere in the app (even when not on these 2 forms) and that would impact the app performance. Let me know if this is acceptable or not.

**Comment by erikalogie** [comment]
> @blushi Not yet, planned to tag her here.
> 
> @erikalogie Hey Erika, I've added the warning modal whenever clicking `VIEW PROFILE`: https://deploy-preview-2144--regen-marketplace.netlify.app/profile/edit Regarding the other nav links (in the header), I would not recommend applying the same behavior here because that would mean we would have to listen to navigation changes everywhere in the app (even when not on these 2 forms) and that would impact the app performance. Let me know if this is acceptable or not.

yeah that's fine

**Review by blushi — APPROVED** [review]
tACK

**Pull request merged**
