### PR TITLE
chore: Use retirement reason instead of TX memo

### PR DESCRIPTION
**Pull request by haveanicedavid**
## Description

Closes: regen-network/regen-registry#1502

~~**NOTE**: https://github.com/regen-network/regen-js/pull/66 will neeed to be merged before this, or you’ll need to pull down that work locally and symlink to properly test - the build will also fail until then. I also was unable to test with a ledger, so am uncertain about amino messages~~

I’m not super familiar with the code related to most of our marketplace functionality, but believe this should include all of the relevant areas

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

(if https://github.com/regen-network/regen-js/pull/66 has’t been merged):
1. in your local `regen-js`, pull down the branch from https://github.com/regen-network/regen-js/pull/66 (`feat-proto-upgrade-regenv5`) & build 
2. Symlink that to your local `regen-web` setup
3. test features 

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have…

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by blushi — CHANGES_REQUESTED** [review]
We need the same changes in `useCreditSendSubmit` and `useCreateBatchSubmit` as well

**Comment by blushi** [comment]
@haveanicedavid I've just published 0.6.0 for https://www.npmjs.com/package/@regen-network/api?activeTab=readme so you can use it here

**Comment by wgwz** [comment]
tACK - i tested buy w/ retire from a project and the storefront, send w/ retire, retire from my portfolio and retire w/ take from basket. LGTM!

i could see the retirement_reason in the tx's, i.e.:
https://redwood.regen.aneka.io/txs/7433FA8076FAF01539BD87E77F6D06384CD222D5FD83D22D83ACBBC5AEC4C6A3

i was unsure what to test re. changes in, LMK if you'd like me to test something
- `web-registry/src/features/ecocredit/CreateBatchBySteps/hooks/useCreateBatchSubmit.ts`

**Review by wgwz — APPROVED** [review]

**Review by flagrede — APPROVED** [review]
tACK

**Comment by blushi** [comment]
> 



> tACK - i tested buy w/ retire from a project and the storefront, send w/ retire, retire from my portfolio and retire w/ take from basket. LGTM!
> 
> i could see the retirement_reason in the tx's, i.e.: https://redwood.regen.aneka.io/txs/7433FA8076FAF01539BD87E77F6D06384CD222D5FD83D22D83ACBBC5AEC4C6A3
> 
> i was unsure what to test re. changes in, LMK if you'd like me to test something
> 
> * `web-registry/src/features/ecocredit/CreateBatchBySteps/hooks/useCreateBatchSubmit.ts`

We have a batch creation form at /ecocredits/create-batch but not sure if that's fully functional yet so ok to skip this I guess

**Comment by erikalogie** [comment]
@blushi this looks good to me!

**Review by blushi — APPROVED** [review]

**Pull request merged**
