### PR TITLE
Home page tweaks per Sarah Bs request

### PR DESCRIPTION
**Pull request by haveanicedavid**
## Description

Closes: regen-network/regen-registry#839

Reordered some homepage sections + changed an image (and added gradient for parity) and removed the email submit form. Per Sarah B's request 

EDIT: 
I made this more sustainable by adding a new section to the sanity CMS (see https://github.com/regen-network/regen-sanity/pull/13) so we can manage text + background image. Also changed location of a topo background as per Erika's request

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] provided a link to the relevant issue or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles 
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@haveanicedavid could you create an issue and add some estimate so we can track it as part of the sprint?

**Comment by haveanicedavid** [comment]
> @haveanicedavid could you create an issue and add some estimate so we can track it as part of the sprint?

@blushi Done: https://app.zenhub.com/workspaces/regen-registry-5f8998bec8958d000f4609e2/issues/regen-network/regen-registry/839

**Review by mhagel — APPROVED** [review]

**Review by blushi — CHANGES_REQUESTED** [review]
This section looks useless now that there's no more email submission form, maybe we should just remove the whole section?

image

**Comment by blushi** [comment]
> @blushi I'll swap this out for another hero section, but they requested to leave the core section (and they'll change the content through sanity).

Oh ok, then this should be done as soon as this gets merged so that we don't have this for too long ;)

**Comment by haveanicedavid** [comment]
@blushi I've updated to create a new section and restore the previous newsletter section + made a few tweaks Erika asked for. Also added the background image + text to the `HomePageWeb` section on sanity (so the text won't change until deployed), but we'll need to merge this PR first: https://github.com/regen-network/regen-sanity/pull/13

**Review by victordelval — APPROVED** [review]

**Pull request merged**
