### PR TITLE
feat: add off-chain projects to projects page

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/regen-web#2077

- display off-chain projects on `/projects`
- add off-chain projects filter

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1. https://deploy-preview-2101--regen-marketplace.netlify.app/projects/1
2. toggle both filters to see off-chains projects

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie you can check that we display off-chain projects and filter them here: https://deploy-preview-2101--regen-marketplace.netlify.app/projects/1

**Comment by erikalogie** [comment]
> @erikalogie you can check that we display off-chain projects and filter them here: https://deploy-preview-2101--regen-marketplace.netlify.app/projects/1

Hey @flagrede this looks pretty good. I would change the text next to the checkbox to say "show off-chain **projects**" and then the tooltip should say "Off-chain projects are under development and have not yet been created on the Regen Ledger blockchain."

Also there is a small spacing issue on mobile: https://monosnap.com/file/7LJDuzLWVftLelNrevE9LGxPWAV6Bt

**Comment by blushi** [comment]
While working on another issue, I've realized that there's a number of "draft" off-chain projects in the prod db that Sam had created then might have run into issues so created another one. So I'm gonna delete those, else they would appear on the projects page as soon as we publish this, since we've marked all existing projects as approved (only future projects will be marked as not approved by default).

**Comment by erikalogie** [comment]
Also I'm just questioning whether off-chain vs on-chain project is the best user-facing way to frame this, as some users might not know anything about blockchain. I realize that the work is already done on this so I don't want to rock the boat too much, but what about framing as "projects with credits for sale" vs projects without? I know it is not the same thing technically but in effect is the same thing 98% of the time. Curious what @clevinson would have to say here.

**Comment by flagrede** [comment]
@blushi are there still some things on hold for this PR to move forward?

**Comment by blushi** [comment]
> @blushi are there still some things on hold for this PR to move forward?

I believe it would be nice to get some feedback regarding @erikalogie latest comment just above before merging.

**Comment by erikalogie** [comment]
Cory hasn't commented here so let's just move forward with this and we can change it later

**Comment by flagrede** [comment]
@blushi Actually I think it might be because you need to google community projects at the same time (all off-chain projects seem to be of community type).

**Comment by blushi** [comment]
> @blushi Actually I think it might be because you need to _toggle_ community projects at the same time (all off-chain projects on staging seem to be of community type).

Strictly speaking, not all off-chain projects on staging are community projects (meaning the credit class id is not on sanity), it's because we base our community project check on the on-chain credit class id so if there's no on-chain project yet, it will necessarily be considered as community project.
If we don't change how it works currently, users will necessarily need to toggle both checkboxes to see off-chain projects, meaning you can't see **only** off-chain projects because there might be some on-chain community projects shown there too. Maybe that's fine, I'm not sure. Thoughts @erikalogie?

**Comment by erikalogie** [comment]
> @erikalogie another question, on prod, the carbonplus grasslands off chain projects would get displayed, do we want to filter them out or not? see my initial message: [#2077 (comment)](https://github.com/regen-network/regen-web/issues/2077#issuecomment-1709605225)
> 
> @flagrede while testing, somehow I'm still seeing the same number of pages and projects (54) when enabling the off chain projects filter. EDIT: ok I think I know why, this might be because the handle->slug rename. I'll merge #2129 and this should work.

I think we would want to display the CarbonPlus Grasslands projects

**Comment by erikalogie** [comment]
> > @blushi Actually I think it might be because you need to _toggle_ community projects at the same time (all off-chain projects on staging seem to be of community type).
> 
> Strictly speaking, not all off-chain projects on staging are community projects (meaning the credit class id is not on sanity), it's because we base our community project check on the on-chain credit class id so if there's no on-chain project yet, it will necessarily be considered as community project. If we don't change how it works currently, users will necessarily need to toggle both checkboxes to see off-chain projects, meaning you can't see **only** off-chain projects because there might be some on-chain community projects shown there too. Maybe that's fine, I'm not sure. Thoughts @erikalogie?

This doesn't sound like what the user would expect here.

**Comment by flagrede** [comment]
@blushi @erikalogie I also think it's a bit weird but I thought that was what we wanted.
Since that doesn't seem to be the case I separated the community from the off-chain filter, they should now work independently.

**Comment by erikalogie** [comment]
@flagrede ok this looks good, thanks!

**Review by blushi — APPROVED** [review]
tACK

**Pull request merged**
