### PR TITLE
fix: APP-95 projects from a Keplr wallet login show up when logged in via a new account

### PR DESCRIPTION
**Pull request by blushi**
## Description

https://regennetwork.atlassian.net/browse/APP-95?atlOrigin=eyJpIjoiMTNlOTgxY2YwOWIyNDZhMThmNDgzNGNhZDY2Njc2YjAiLCJwIjoiaiJ9

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

https://deploy-preview-2345--regen-marketplace.netlify.app/
This can be tested if you login with a web3 account, then wait enough for the login session to expire (24 hours) or for testing purposes in order to mimic that, you can just open the dev tool, go to "Application" tab, then cookies and delete the two cookies with name session and session.sig and reload. You'll get logged out.
Finally, log back in with another web2 account. You should only see the projects from this web2 account, while if you do the same on dev.app.regen.network, you'll also get the projects from the web3 account.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie @clevinson see testing instructions

**Review by aaronc — APPROVED** [review]
utACK

**Comment by clevinson** [comment]
@blushi I was able to verify the bug exists on http://dev.app.regen.network (using the cookie deletion method you shared here).  However, when testing on the deploy preview, I was not able to force a logout with cookie deletion. I found the two session cookies, and after deleting them remained logged in to the app with the current wallet user.

Let me know if you are able to reproduce this. I'm guessing this is unexpected behavior.

**Comment by blushi** [comment]
> @blushi I was able to verify the bug exists on http://dev.app.regen.network (using the cookie deletion method you shared here). However, when testing on the deploy preview, I was not able to force a logout with cookie deletion. I found the two session cookies, and after deleting them remained logged in to the app with the current wallet user.
> 
> Let me know if you are able to reproduce this. I'm guessing this is unexpected behavior.

I can't reproduce this. The changes here shouldn't have any effect on this (this only changes how we query projects by admin). Could you provide a video of this?

**Comment by blushi** [comment]
> > @blushi I was able to verify the bug exists on http://dev.app.regen.network (using the cookie deletion method you shared here). However, when testing on the deploy preview, I was not able to force a logout with cookie deletion. I found the two session cookies, and after deleting them remained logged in to the app with the current wallet user.
> > Let me know if you are able to reproduce this. I'm guessing this is unexpected behavior.
> 
> I can't reproduce this. The changes here shouldn't have any effect on this (this only changes how we query projects by admin). Could you provide a video of this?

After debugging this with @clevinson and some further investigation on my side, we realized that this was not particularly related to this deploy preview, but all deploy previews in general while testing on Brave browser, which blocks third party cookies by default. Unblocking those for the deploy preview that is being tested should fix any unexpected behavior.

**Comment by blushi** [comment]
> > > @blushi I was able to verify the bug exists on http://dev.app.regen.network (using the cookie deletion method you shared here). However, when testing on the deploy preview, I was not able to force a logout with cookie deletion. I found the two session cookies, and after deleting them remained logged in to the app with the current wallet user.
> > > Let me know if you are able to reproduce this. I'm guessing this is unexpected behavior.
> > 
> > 
> > I can't reproduce this. The changes here shouldn't have any effect on this (this only changes how we query projects by admin). Could you provide a video of this?
> 
> After debugging this with @clevinson and some further investigation on my side, we realized that this was not particularly related to this deploy preview, but all deploy previews in general while testing on Brave browser, which blocks third party cookies by default. Unblocking those for the deploy preview that is being tested should fix any unexpected behavior. @clevinson could you make sure to do that while testing?

@clevinson could you try again based on my comment above?

**Comment by clevinson** [comment]
@blushi I just tried logging in with this deploy preview on both Chrome and Brave (with 3rd party cookies enabled).  In both cases I cannot log in and get the following error (in the UI with a red banner at the top of my screen):

"ReferenceError: require is not defined"

**Comment by blushi** [comment]
> @blushi I just tried logging in with this deploy preview on both Chrome and Brave (with 3rd party cookies enabled). In both cases I cannot log in and get the following error (in the UI with a red banner at the top of my screen):
> 
> "ReferenceError: require is not defined"

I remember we faced an error somewhat similar at some point in the past: https://github.com/regen-network/regen-web/pull/2066
This was coming from @ledgerhq/live-network code, the dependency patch was then removed later because it was not a dependency anymore (indirect). It looks like it's back now so I've added back the patch for the currently used version. That should fix it.

**Review by clevinson — APPROVED** [review]

**Pull request merged**
