### PR TITLE
feat: APP-140 add a popup with basic info about offchain project pages for users

### PR DESCRIPTION
**Pull request by blushi**
## Description

https://regennetwork.atlassian.net/browse/APP-140?atlOrigin=eyJpIjoiZjJkNjE5NTllY2NjNDdmMWFmZDA4MjU2YWE1MTEyMGMiLCJwIjoiaiJ9

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

 From https://deploy-preview-2374--regen-marketplace.netlify.app/
1. Log in with a web2 account and create a project (either from list a project top nav button or from the create project button on your profile page), you should see the popup on top of the basic info form
2. Log in with a web3 account that is an issuer and create a project:
   - if you choose a credit class then you'll get to the basic info form without the popup being displayed
   - if you do no choose any credit class then you'll get to the basic info form with the popup on top of it, as in 1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie @clevinson see testing instructions

**Review by aaronc — APPROVED** [review]
utACK

**Comment by blushi** [comment]
> One thing I noticed is that I get this screen if initiating the flow from this address: regen1ttl8xqmyt346hgp79yh949c4l8gw4wz9rmqcrg. I've never seen this before, and I thought this screen should be hidden for not credit issuers. Screenshot 2024-05-23 at 9 18 16 AM
> 
> I'm not seeing the screen above when connecting to the same address on dev and creating project.

Looking at the URL on the screenshot, you're using the dev app so I'm a bit confused.
Could you take a video? Are you creating a project from "list a project" in the header or the "create project" button from the profile page?

**Comment by erikalogie** [comment]
> * if you choose a credit class then you'll get to the basic info form without the popup being displayed

I can't seem to reproduce it and not sure how I got onto the dev branch instead of the deploy preview! One other thing that I'm noticing that has happened a number of times now is after I log in, the first time I click on the "create project" button from the projects tab on my portfolio, it doesn't activate the popup. Then if I click "list a project" in the navigation, and then cancel out, then click the "create project" button, it works and shows the popup.

**Comment by erikalogie** [comment]
Also now I'm logged in with email and clicking on the "create project" button and it is prompting me to log in with keplr, but its not doing it if I click the "list project button". I think we shouldn't force them to log in with keplr to create a project.

https://github.com/regen-network/regen-web/assets/8460237/5ef88efa-68d8-494b-80bc-e79f36b6a1e4

**Comment by blushi** [comment]
> Also now I'm logged in with email and clicking on the "create project" button and it is prompting me to log in with keplr, but its not doing it if I click the "list project button". I think we shouldn't force them to log in with keplr to create a project.
> 
>  video.mov

This is because you log in with an account that has a wallet address attached to it, but it's not the one selected in Keplr.
Since this address is an issuer, it redirects you to the choose credit class page, which is only available if connected to Keplr. This is quite an edge case, unrelated to those changes. I guess either:
- we can just redirect to the basic info form but that might be a bit confusing for the user that sometimes it goes to choose credit class (when the wallet address is connected) and some other times to basic info (when it's not)
- or we display a warning telling the user to switch to the correct wallet address in Keplr

**Comment by erikalogie** [comment]
> > Also now I'm logged in with email and clicking on the "create project" button and it is prompting me to log in with keplr, but its not doing it if I click the "list project button". I think we shouldn't force them to log in with keplr to create a project.
> > video.mov
> 
> This is because you log in with an account that has a wallet address attached to it, but it's not the one selected in Keplr. Since this address is an issuer, it redirects you to the choose credit class page, which is only available if connected to Keplr. This is quite an edge case, unrelated to those changes. I guess either:
> 
> * we can just redirect to the basic info form but that might be a bit confusing for the user that sometimes it goes to choose credit class (when the wallet address is connected) and some other times to basic info (when it's not)
> * or we display a warning telling the user to switch to the correct wallet address in Keplr

Ah ok, I've made this Jira follow up task: https://regennetwork.atlassian.net/browse/APP-172

**Comment by blushi** [comment]
> > * if you choose a credit class then you'll get to the basic info form without the popup being displayed
> 
> I can't seem to reproduce it and not sure how I got onto the dev branch instead of the deploy preview! One other thing that I'm noticing that has happened a number of times now is after I log in, the first time I click on the "create project" button from the projects tab on my portfolio, it doesn't activate the popup. Then if I click "list a project" in the navigation, and then cancel out, then click the "create project" button, it works and shows the popup. This doesn't seem to happen consistently though, but has happened randomly while I'm testing.

@erikalogie I believe this should be fixed now, could you test again?

**Comment by erikalogie** [comment]
LGTM

**Pull request merged**
