### PR TITLE
fix: APP-335 add icon for video files in data post map

### PR DESCRIPTION
**Pull request by r41ph**
## Description

https://regennetwork.atlassian.net/browse/APP-335

---

### Author Checklist

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1. https://deploy-preview-2463--regen-marketplace.netlify.app/post/regen:13toVhek5wriSdpWzXyu4PUTvoAxuXuzmwjJLsbQbh7NrsZUEtinWTo.rdf

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by r41ph** [comment]
@erikalogie see testing instructions. 

I've used a temporary icon to address the bug (Youtube icon from our icons library). If you want to change it, I'll replace it once provided.

**Comment by erikalogie** [comment]
> 1. https://deploy-preview-2463--regen-marketplace.netlify.app/post/regen:13toVhek5wriSdpWzXyu4PUTvoAxuXuzmwjJLsbQbh7NrsZUEtinWTo.rdf

Great! Here is the video icon: https://www.figma.com/design/MuSpCtCdU2ns4cFAsPfvsx/Text-Styles-%26-Components?node-id=8-0&t=8hHdqv9bZ6nGU0o2-1. One thing to note is that the color of the little video icon should change to black and it's background should change to white when the little window is closed.

**Comment by r41ph** [comment]
@erikalogie icon updated, please have a look

**Review by blushi — APPROVED** [review]
tACK

**Pull request merged**
