### PR TITLE
fix: add state to control visibility of files window

### PR DESCRIPTION
**Pull request by r41ph**
## Description

https://regennetwork.atlassian.net/browse/APP-279

---

### Author Checklist

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1. Go to a post page of a post with files and verify that the files icons (the marker in the map) toggles the files window

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by r41ph** [comment]
@erikalogie @clevinson see testing instructions

**Comment by erikalogie** [comment]
@r41ph https://www.loom.com/share/534360f093e94dd596b20e1e30fad9f3

**Comment by r41ph** [comment]
@erikalogie thanks for the video. Have a look again when you can. Now when multiple files in different locations should work as mentioned in the video.

**Comment by erikalogie** [comment]
@r41ph that looks good, nice work

**Comment by erikalogie** [comment]
> **marie left a comment:**
> 
> If I close the file preview, then click on another file **from the sidebar on the right**, then it selects the file on the map but does not open the preview, should we re-open up the preview too in this case? @erikalogie
> 
> recording
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-2437--regen-marketplace.netlify.app/post/regen:13toVfzMtPxRbRC4y2GVPKUpC9jUinKJtk5TW99qHigDi6XQNuXqLwr.rdf) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=66cdcc422c7d810008aa444c&commentID=66d02aad59fbfdbce0c01a82&resolution=resolved)

Yes, definitely! I failed to test this, good catch!

**Comment by r41ph** [comment]
@erikalogie @blushi see updated version

**Comment by erikalogie** [comment]
LGTM

**Review by blushi — APPROVED** [review]
tACK

**Pull request merged**
