### PR TITLE
fix: APP-139 upload modal layout

### PR DESCRIPTION
**Pull request by blushi**
## Description

https://regennetwork.atlassian.net/browse/APP-139?atlOrigin=eyJpIjoiZTI1ZTUyN2QxMmIwNDBhOGJlYTQ3MmZhMmJjOTJkNTciLCJwIjoiaiJ9

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

From https://deploy-preview-2375--regen-marketplace.netlify.app, log in and create/edit a project
Go to the media form and try adding photos, check the upload modal layout on all screen sizes. 

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie @clevinson see testing instructions

**Comment by erikalogie** [comment]
Looks good! I did notice that if I try to click the "edit photo" pencil button, it does not activate the modal. Is this related? For example here: https://deploy-preview-2375--regen-marketplace.netlify.app/project-pages/C04-002/edit/media

**Review by aaronc — APPROVED** [review]
utACK

**Comment by blushi** [comment]
> Looks good! I did notice that if I try to click the "edit photo" pencil button, it does not activate the modal. Is this related? For example here: https://deploy-preview-2375--regen-marketplace.netlify.app/project-pages/C04-002/edit/media

This is unrelated but indeed there's a CORS error when trying to fetch the image and the modal doesn't open because of this error, so I'll open up a separate task to address that and merge this.

**Pull request merged**
