### PR TITLE
fix: APP-486 handle social and cultural card

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: APP-486

Enable social and cultural card and change duration max value and tooltip for V4 projects.

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1.

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie You can check that the social and cultural card is displayed here for V4 projects, along with new max value and tooltip for the duration card: https://deploy-preview-2554--terrasos.netlify.app/project/test-terrasos-project

**Comment by erikalogie** [comment]
LGTM

**Comment by erikalogie** [comment]
One small comment, the paragraph should have a period at the end to match the other cards.

**Comment by erikalogie** [comment]
@flagrede you can use the updated descriptions for each level here: https://www.figma.com/design/brkxGV5qNOkZUp0YQl1cxO/Terrasos-Phase-1?node-id=1295-242275&t=HZDUGb5LX9gNqqeD-1 Thanks!

**Comment by blushi** [comment]
image

The title shouldn't be "Social and Cultural Index" but the actual value ("very high", etc.)

**Review by blushi — APPROVED** [review]
tACK

**Comment by erikalogie** [comment]
LGTM!

**Pull request merged**
