### PR TITLE
fix: pagination credit batches

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/regen-registry#1662

Remove hidden from current pagination count.

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1. Go to https://deploy-preview-1906--regen-registry.netlify.app/ecocredits/accounts/regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46/portfolio
2. navigate to page `21-24`

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie you can check the pagination bug fix here: https://deploy-preview-1906--regen-registry.netlify.app/ecocredits/accounts/regen1df675r9vnf7pdedn4sf26svdsem3ugavgxmy46/portfolio
There's an hidden row on the page `21-24`

**Comment by erikalogie** [comment]
@flagrede this looks good. As you said on slack the rest will be solved with the ledger upgrade

**Comment by blushi** [comment]
@wgwz see underlying issue on regen-ledger: https://github.com/regen-network/regen-ledger/issues/1889

**Comment by wgwz** [comment]
@flagrede @blushi thanks for the context, that makes sense now. indeed, it'll be best to fix that in the ledger. i have no problem with this in the mean time!

**Review by wgwz — APPROVED** [review]
tACK

**Pull request merged**
