### PR TITLE
fix: first project card spacing, title and icon

### PR DESCRIPTION
**Pull request by blushi**
## Description

Closes: regen-network/regen-registry#1628

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [x] provided a link to the relevant issue or specification
- [x] provided instructions on how to test
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### How to test

1. Go to https://deploy-preview-1991--regen-registry.netlify.app/ecocredits/projects and login using an address that is a credit class issuer but doesn't have any project yet
2. You should see the "create project" card with the fixes

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by blushi** [comment]
@erikalogie see testing instructions above

**Comment by erikalogie** [comment]
@blushi which address "is a credit class issuer but doesn't have any project yet"?

**Review by ryanchristo — APPROVED** [review]
tACk. One thing I noticed though is the create project and create batch cards have different widths, one is not full width and the other is. Not sure if this was intentional, if it can be quickly addressed here, or if we should handle separately.

Screenshot from 2023-07-31 09-25-18

Screenshot from 2023-07-31 09-22-11

**Comment by erikalogie** [comment]
> tACk. One thing I noticed though is the create project and create batch cards have different widths, one is full width and the other is not. I'm not sure if this was intentional, if it can be quickly addressed here, or if we should handle separately.
> 
> Screenshot from 2023-07-31 09-25-18
> 
> Screenshot from 2023-07-31 09-22-11

this was intentional

**Comment by blushi** [comment]
> @blushi which address "is a credit class issuer but doesn't have any project yet"?

It seems like your address regen1ttl8xqmyt346hgp79yh949c4l8gw4wz9rmqcrg is an issuer without any project yet

**Pull request merged**
