### PR TITLE
fix: impact cards container

### PR DESCRIPTION
**Pull request by flagrede**
## Description

Closes: regen-network/regen-registry#1681

Display impact cards container overflow.

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] provided a link to the relevant issue or specification
- [ ] provided instructions on how to test
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### How to test

1. https://deploy-preview-1892--regen-registry.netlify.app/project/C02-018

### Reviewers Checklist

_All items are required. Please add a note if the item is not applicable and please **add
your handle next to the items reviewed if you only reviewed selected items**._

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed code correctness and readability
- [ ] verified React components follow DRY principles
- [ ] reviewed documentation is accurate
- [ ] reviewed tests
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by flagrede** [comment]
@erikalogie You can test the fix on the impact cards section here: https://deploy-preview-1892--regen-registry.netlify.app/project/C02-018

**Review by blushi — APPROVED** [review]

**Comment by erikalogie** [comment]
@flagrede how does it look with just 3 impact cards?

**Comment by flagrede** [comment]
@erikalogie like it used to be (I manually delete one).
image

**Comment by erikalogie** [comment]
@flagrede can I see this on the deploy preview somewhere?

**Pull request merged**
